import { v4 as uuidv4 } from 'uuid';

export const initialContext = {
  selected: {
    exampleId: ""
  },
  canvases: [],
  specs: {
    events: [
      {
        type: "ADD_CANVAS",
      },
      {
        type: "RENAME_CANVAS",
        canvasId: "",
        newName: "",
      },
      {
        type: "REMOVE_CANVAS",
        canvasId: "",
      },
      {
        type: "UPDATE_CANVAS",
        canvas: {},
      },
      {
        type: "MOVE_WIDGET_TO_CANVAS",
        widgetId: "",
        sourceCanvasId: "",
        targetCanvasId: "",
      },
      {
        type: "OPEN_WIDGET_POPOVER",
        position: { x: 0, y: 0 },
      },
      {
        type: "CLOSE_WIDGET_POPOVER",
      },
      {
        type: "CREATE_WIDGET",
        title: "",
        targetCanvasId: "",
      },
      {
        type: "TOGGLE_GLOBAL_JSON_MODAL",
      },
      {
        type: "TOGGLE_LOAD_FROM_MENU",
      },
      {
        type: "LOAD_EXAMPLE",
        example: ["analytics", "project", "personal"],
      },
      {
        type: "NEW_SESSION",
      },
    ]
  },
  presets: {
    emptyCanvas: {
      id: uuidv4(),
      name: 'Canvas 1',
      widgets: [],
      config: {
        cols: 12,
        rowHeight: 100,
        isBounded: false,
        maxRows: 12,
        preventCollision: false,
        allowOverlap: false,
        compactType: 'vertical',
        margin: [10, 10]
      }
    }
  },
  result: {
    totalWidgets: 0,
    summary: {
      canvasCount: 0,
      canvasNames: [],
      widgetsByCanvas: {}
    },
  },
  data: [
    {
      id: 'analytics',
      name: 'Analytics Dashboard',
      description: 'Data visualization with metrics and charts',
      data: [
        {
          id: uuidv4(),
          name: 'Overview',
          widgets: [
            {
              i: uuidv4(),
              x: 0,
              y: 0,
              w: 6,
              h: 4,
              name: 'Daily Active Users',
              content: 'Chart: Daily Active Users',
              canvasId: '1'
            },
            {
              i: uuidv4(),
              x: 6,
              y: 0,
              w: 6,
              h: 4,
              name: 'Revenue',
              content: 'Chart: Revenue',
              canvasId: '1'
            },
            {
              i: uuidv4(),
              x: 0,
              y: 4,
              w: 4,
              h: 4,
              name: 'Conversion Rate',
              content: 'Metric: Conversion Rate',
              canvasId: '1'
            },
            {
              i: uuidv4(),
              x: 4,
              y: 4,
              w: 8,
              h: 4,
              name: 'User Retention',
              content: 'Chart: User Retention',
              canvasId: '1'
            }
          ],
          config: {
            cols: 12,
            rowHeight: 100,
            isBounded: true,
            maxRows: 12,
            preventCollision: false,
            allowOverlap: false,
            compactType: 'vertical',
            margin: [10, 10]
          }
        },
        {
          id: uuidv4(),
          name: 'User Metrics',
          widgets: [
            {
              i: uuidv4(),
              x: 0,
              y: 0,
              w: 12,
              h: 4,
              name: 'User Growth',
              content: 'Chart: User Growth Over Time',
              canvasId: '2'
            },
            {
              i: uuidv4(),
              x: 0,
              y: 4,
              w: 6,
              h: 4,
              name: 'Demographics',
              content: 'Chart: User Demographics',
              canvasId: '2'
            },
            {
              i: uuidv4(),
              x: 6,
              y: 4,
              w: 6,
              h: 4,
              name: 'Geographical Distribution',
              content: 'Map: User Locations',
              canvasId: '2'
            }
          ],
          config: {
            cols: 12,
            rowHeight: 100,
            isBounded: true,
            maxRows: 12,
            preventCollision: false,
            allowOverlap: false,
            compactType: 'vertical',
            margin: [10, 10]
          }
        }
      ],
      canvasCount: 0,
      widgetCount: 0
    },
    {
      id: 'project',
      name: 'Project Management',
      description: 'Task tracking and project overview',
      data: [
        {
          id: uuidv4(),
          name: 'Project Overview',
          widgets: [
            {
              i: uuidv4(),
              x: 0,
              y: 0,
              w: 4,
              h: 4,
              name: 'Project Status',
              content: 'Status: In Progress',
              canvasId: '1'
            },
            {
              i: uuidv4(),
              x: 4,
              y: 0,
              w: 8,
              h: 4,
              name: 'Timeline',
              content: 'Gantt Chart: Project Timeline',
              canvasId: '1'
            },
            {
              i: uuidv4(),
              x: 0,
              y: 4,
              w: 6,
              h: 6,
              name: 'Task Distribution',
              content: 'Chart: Tasks by Assignee',
              canvasId: '1'
            },
            {
              i: uuidv4(),
              x: 6,
              y: 4,
              w: 6,
              h: 6,
              name: 'Recent Activity',
              content: 'Feed: Recent Updates',
              canvasId: '1'
            }
          ],
          config: {
            cols: 12,
            rowHeight: 80,
            isBounded: false,
            maxRows: 15,
            preventCollision: true,
            allowOverlap: false,
            compactType: 'vertical',
            margin: [15, 15]
          }
        },
        {
          id: uuidv4(),
          name: 'Resources',
          widgets: [
            {
              i: uuidv4(),
              x: 0,
              y: 0,
              w: 12,
              h: 3,
              name: 'Team Members',
              content: 'List: Team Members and Roles',
              canvasId: '2'
            },
            {
              i: uuidv4(),
              x: 0,
              y: 3,
              w: 6,
              h: 5,
              name: 'Budget Allocation',
              content: 'Chart: Budget Breakdown',
              canvasId: '2'
            },
            {
              i: uuidv4(),
              x: 6,
              y: 3,
              w: 6,
              h: 5,
              name: 'Resource Utilization',
              content: 'Chart: Resource Usage',
              canvasId: '2'
            }
          ],
          config: {
            cols: 12,
            rowHeight: 80,
            isBounded: false,
            maxRows: 15,
            preventCollision: true,
            allowOverlap: false,
            compactType: 'vertical',
            margin: [15, 15]
          }
        },
        {
          id: uuidv4(),
          name: 'Tasks',
          widgets: [
            {
              i: uuidv4(),
              x: 0,
              y: 0,
              w: 4,
              h: 8,
              name: 'To Do',
              content: 'List: Pending Tasks',
              canvasId: '3'
            },
            {
              i: uuidv4(),
              x: 4,
              y: 0,
              w: 4,
              h: 8,
              name: 'In Progress',
              content: 'List: Tasks in Progress',
              canvasId: '3'
            },
            {
              i: uuidv4(),
              x: 8,
              y: 0,
              w: 4,
              h: 8,
              name: 'Completed',
              content: 'List: Completed Tasks',
              canvasId: '3'
            }
          ],
          config: {
            cols: 12,
            rowHeight: 80,
            isBounded: false,
            maxRows: 15,
            preventCollision: true,
            allowOverlap: false,
            compactType: 'vertical',
            margin: [15, 15]
          }
        }
      ],
      canvasCount: 0,
      widgetCount: 0
    },
    {
      id: 'personal',
      name: 'Personal Dashboard',
      description: 'Daily overview and personal metrics',
      data: [
        {
          id: uuidv4(),
          name: 'Daily Overview',
          widgets: [
            {
              i: uuidv4(),
              x: 0,
              y: 0,
              w: 4,
              h: 3,
              name: 'Weather',
              content: 'Widget: Current Weather',
              canvasId: '1'
            },
            {
              i: uuidv4(),
              x: 4,
              y: 0,
              w: 8,
              h: 3,
              name: 'Calendar',
              content: 'Widget: Today\'s Events',
              canvasId: '1'
            },
            {
              i: uuidv4(),
              x: 0,
              y: 3,
              w: 6,
              h: 4,
              name: 'Tasks',
              content: 'List: Today\'s Tasks',
              canvasId: '1'
            },
            {
              i: uuidv4(),
              x: 6,
              y: 3,
              w: 6,
              h: 4,
              name: 'Notes',
              content: 'Widget: Quick Notes',
              canvasId: '1'
            }
          ],
          config: {
            cols: 12,
            rowHeight: 90,
            isBounded: true,
            maxRows: 10,
            preventCollision: false,
            allowOverlap: false,
            compactType: 'vertical',
            margin: [10, 10]
          }
        },
        {
          id: uuidv4(),
          name: 'Health & Fitness',
          widgets: [
            {
              i: uuidv4(),
              x: 0,
              y: 0,
              w: 6,
              h: 4,
              name: 'Step Counter',
              content: 'Widget: Daily Steps',
              canvasId: '2'
            },
            {
              i: uuidv4(),
              x: 6,
              y: 0,
              w: 6,
              h: 4,
              name: 'Water Intake',
              content: 'Widget: Water Consumption',
              canvasId: '2'
            },
            {
              i: uuidv4(),
              x: 0,
              y: 4,
              w: 12,
              h: 4,
              name: 'Workout Plan',
              content: 'Widget: Weekly Workout Schedule',
              canvasId: '2'
            }
          ],
          config: {
            cols: 12,
            rowHeight: 90,
            isBounded: true,
            maxRows: 10,
            preventCollision: false,
            allowOverlap: false,
            compactType: 'vertical',
            margin: [10, 10]
          }
        }
      ],
      canvasCount: 0,
      widgetCount: 0
    }
  ],
  components: {
    ReactGridLayoutApp: {
      isWidgetPopoverOpen: false,
      widgetPopoverPosition: { x: 0, y: 0 },
      isGlobalJSONModalOpen: false,
      isLoadFromMenuOpen: false,
    },
    CanvasHeader: {
      isEditing: false,
      newName: "",
      isSettingsOpen: false,
      isJSONModalOpen: false,
      isWidgetPopoverOpen: false,
      newConfig: {},
    }
  }
}



export const originalPresets = {
  reactGridLayoutDemo: {
    empty: {
      defaultProps: {},
      additionalProps: {
        disabled: true,
      },
    },
    showcase: {
      defaultProps: {
        className: "layout",
        rowHeight: 30,
        cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
        layout: {
          lg: [
            {
              w: 2,
              h: 2,
              minH: 2,
              minW: 2,
              x: 2,
              y: 0,
              i: "0",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 5,
              x: 2,
              y: 0,
              i: "1",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 2,
              x: 8,
              y: 0,
              i: "2",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 3,
              x: 2,
              y: 0,
              i: "3",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 3,
              x: 4,
              y: 0,
              i: "4",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 5,
              x: 8,
              y: 0,
              i: "5",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 4,
              x: 2,
              y: 4,
              i: "6",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 5,
              x: 10,
              y: 5,
              i: "7",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 5,
              x: 4,
              y: 5,
              i: "8",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 3,
              x: 8,
              y: 3,
              i: "9",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 4,
              x: 6,
              y: 4,
              i: "10",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 2,
              x: 4,
              y: 2,
              i: "11",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 4,
              x: 2,
              y: 8,
              i: "12",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 3,
              x: 8,
              y: 6,
              i: "13",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 2,
              x: 2,
              y: 4,
              i: "14",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 3,
              x: 8,
              y: 6,
              i: "15",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 4,
              x: 4,
              y: 8,
              i: "16",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 4,
              x: 6,
              y: 8,
              i: "17",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 3,
              x: 6,
              y: 9,
              i: "18",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 2,
              x: 2,
              y: 6,
              i: "19",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 3,
              x: 8,
              y: 9,
              i: "20",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 4,
              x: 4,
              y: 12,
              i: "21",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 3,
              x: 6,
              y: 9,
              i: "22",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 3,
              x: 6,
              y: 9,
              i: "23",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 3,
              x: 8,
              y: 12,
              i: "24",
              static: false,
              resizeHandles: ["se"],
            },
          ],
        },
      },
      additionalProps: {
        responsive: true,
      },
      state: {
        currentBreakpoint: "lg",
        compactType: "vertical",
        resizeHandles: ["se"],
        mounted: false,
        layouts: {
          lg: [
            {
              w: 2,
              h: 2,
              x: 2,
              y: 0,
              i: "0",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 5,
              x: 2,
              y: 0,
              i: "1",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 2,
              x: 8,
              y: 0,
              i: "2",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 3,
              x: 2,
              y: 0,
              i: "3",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 3,
              x: 4,
              y: 0,
              i: "4",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 5,
              x: 8,
              y: 0,
              i: "5",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 4,
              x: 2,
              y: 4,
              i: "6",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 5,
              x: 10,
              y: 5,
              i: "7",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 5,
              x: 4,
              y: 5,
              i: "8",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 3,
              x: 8,
              y: 3,
              i: "9",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 4,
              x: 6,
              y: 4,
              i: "10",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 2,
              x: 4,
              y: 2,
              i: "11",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 4,
              x: 2,
              y: 8,
              i: "12",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 3,
              x: 8,
              y: 6,
              i: "13",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 2,
              x: 2,
              y: 4,
              i: "14",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 3,
              x: 8,
              y: 6,
              i: "15",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 4,
              x: 4,
              y: 8,
              i: "16",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 4,
              x: 6,
              y: 8,
              i: "17",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 3,
              x: 6,
              y: 9,
              i: "18",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 2,
              x: 2,
              y: 6,
              i: "19",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 3,
              x: 8,
              y: 9,
              i: "20",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 4,
              x: 4,
              y: 12,
              i: "21",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 3,
              x: 6,
              y: 9,
              i: "22",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 3,
              x: 6,
              y: 9,
              i: "23",
              static: false,
              resizeHandles: ["se"],
            },
            {
              w: 2,
              h: 3,
              x: 8,
              y: 12,
              i: "24",
              static: false,
              resizeHandles: ["se"],
            },
          ],
        },
      },
    },
    basic: {
      defaultProps: {
        className: "layout",
        items: 5,
        rowHeight: 30,
        cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
        layout: {
          lg: [
            {
              x: 0,
              y: 0,
              w: 2,
              h: 3,
              i: "0",
            },
            {
              x: 2,
              y: 0,
              w: 2,
              h: 2,
              i: "1",
            },
            {
              x: 4,
              y: 0,
              w: 2,
              h: 4,
              i: "2",
            },
            {
              x: 6,
              y: 0,
              w: 2,
              h: 4,
              i: "3",
            },
            {
              x: 8,
              y: 0,
              w: 2,
              h: 4,
              i: "4",
            },
          ],
        },
      },
      additionalProps: {
        responsive: true,
      },
    },
    noDragging: {
      defaultProps: {
        className: "layout",
        isDraggable: false,
        isResizable: false,
        items: 50,
        cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
        rowHeight: 30,
        layout: {
          lg: [
            {
              x: 0,
              y: 0,
              w: 2,
              h: 5,
              i: "0",
            },
            {
              x: 2,
              y: 0,
              w: 2,
              h: 5,
              i: "1",
            },
            {
              x: 4,
              y: 0,
              w: 2,
              h: 2,
              i: "2",
            },
            {
              x: 6,
              y: 0,
              w: 2,
              h: 3,
              i: "3",
            },
            {
              x: 8,
              y: 0,
              w: 2,
              h: 3,
              i: "4",
            },
            {
              x: 10,
              y: 0,
              w: 2,
              h: 4,
              i: "5",
            },
            {
              x: 0,
              y: 3,
              w: 2,
              h: 3,
              i: "6",
            },
            {
              x: 2,
              y: 3,
              w: 2,
              h: 3,
              i: "7",
            },
            {
              x: 4,
              y: 5,
              w: 2,
              h: 5,
              i: "8",
            },
            {
              x: 6,
              y: 5,
              w: 2,
              h: 5,
              i: "9",
            },
            {
              x: 8,
              y: 5,
              w: 2,
              h: 5,
              i: "10",
            },
            {
              x: 10,
              y: 5,
              w: 2,
              h: 5,
              i: "11",
            },
            {
              x: 0,
              y: 10,
              w: 2,
              h: 5,
              i: "12",
            },
            {
              x: 2,
              y: 10,
              w: 2,
              h: 5,
              i: "13",
            },
            {
              x: 4,
              y: 6,
              w: 2,
              h: 3,
              i: "14",
            },
            {
              x: 6,
              y: 6,
              w: 2,
              h: 3,
              i: "15",
            },
            {
              x: 8,
              y: 6,
              w: 2,
              h: 3,
              i: "16",
            },
            {
              x: 10,
              y: 8,
              w: 2,
              h: 4,
              i: "17",
            },
            {
              x: 0,
              y: 12,
              w: 2,
              h: 4,
              i: "18",
            },
            {
              x: 2,
              y: 9,
              w: 2,
              h: 3,
              i: "19",
            },
            {
              x: 4,
              y: 9,
              w: 2,
              h: 3,
              i: "20",
            },
            {
              x: 6,
              y: 9,
              w: 2,
              h: 3,
              i: "21",
            },
            {
              x: 8,
              y: 6,
              w: 2,
              h: 2,
              i: "22",
            },
            {
              x: 10,
              y: 9,
              w: 2,
              h: 3,
              i: "23",
            },
            {
              x: 0,
              y: 8,
              w: 2,
              h: 2,
              i: "24",
            },
            {
              x: 2,
              y: 20,
              w: 2,
              h: 5,
              i: "25",
            },
            {
              x: 4,
              y: 8,
              w: 2,
              h: 2,
              i: "26",
            },
            {
              x: 6,
              y: 16,
              w: 2,
              h: 4,
              i: "27",
            },
            {
              x: 8,
              y: 8,
              w: 2,
              h: 2,
              i: "28",
            },
            {
              x: 10,
              y: 20,
              w: 2,
              h: 5,
              i: "29",
            },
            {
              x: 0,
              y: 20,
              w: 2,
              h: 4,
              i: "30",
            },
            {
              x: 2,
              y: 20,
              w: 2,
              h: 4,
              i: "31",
            },
            {
              x: 4,
              y: 20,
              w: 2,
              h: 4,
              i: "32",
            },
            {
              x: 6,
              y: 25,
              w: 2,
              h: 5,
              i: "33",
            },
            {
              x: 8,
              y: 10,
              w: 2,
              h: 2,
              i: "34",
            },
            {
              x: 10,
              y: 10,
              w: 2,
              h: 2,
              i: "35",
            },
            {
              x: 0,
              y: 30,
              w: 2,
              h: 5,
              i: "36",
            },
            {
              x: 2,
              y: 18,
              w: 2,
              h: 3,
              i: "37",
            },
            {
              x: 4,
              y: 12,
              w: 2,
              h: 2,
              i: "38",
            },
            {
              x: 6,
              y: 12,
              w: 2,
              h: 2,
              i: "39",
            },
            {
              x: 8,
              y: 24,
              w: 2,
              h: 4,
              i: "40",
            },
            {
              x: 10,
              y: 30,
              w: 2,
              h: 5,
              i: "41",
            },
            {
              x: 0,
              y: 14,
              w: 2,
              h: 2,
              i: "42",
            },
            {
              x: 2,
              y: 35,
              w: 2,
              h: 5,
              i: "43",
            },
            {
              x: 4,
              y: 21,
              w: 2,
              h: 3,
              i: "44",
            },
            {
              x: 6,
              y: 35,
              w: 2,
              h: 5,
              i: "45",
            },
            {
              x: 8,
              y: 14,
              w: 2,
              h: 2,
              i: "46",
            },
            {
              x: 10,
              y: 14,
              w: 2,
              h: 2,
              i: "47",
            },
            {
              x: 0,
              y: 40,
              w: 2,
              h: 5,
              i: "48",
            },
            {
              x: 2,
              y: 32,
              w: 2,
              h: 4,
              i: "49",
            },
          ],
        },
      },
      additionalProps: {},
    },
    messy: {
      defaultProps: {
        className: "layout",
        cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
        items: 20,
        layout: {
          lg: [
            {
              x: 0,
              y: 0,
              w: 1,
              h: 5,
              i: "0",
            },
            {
              x: 2,
              y: 0,
              w: 2,
              h: 2,
              i: "1",
            },
            {
              x: 4,
              y: 0,
              w: 1,
              h: 4,
              i: "2",
            },
            {
              x: 6,
              y: 0,
              w: 3,
              h: 3,
              i: "3",
            },
            {
              x: 8,
              y: 0,
              w: 3,
              h: 4,
              i: "4",
            },
            {
              x: 10,
              y: 0,
              w: 1,
              h: 2,
              i: "5",
            },
            {
              x: 0,
              y: 2,
              w: 4,
              h: 2,
              i: "6",
            },
            {
              x: 2,
              y: 4,
              w: 3,
              h: 4,
              i: "7",
            },
            {
              x: 4,
              y: 4,
              w: 2,
              h: 4,
              i: "8",
            },
            {
              x: 6,
              y: 2,
              w: 2,
              h: 2,
              i: "9",
            },
            {
              x: 8,
              y: 3,
              w: 2,
              h: 3,
              i: "10",
            },
            {
              x: 10,
              y: 2,
              w: 4,
              h: 2,
              i: "11",
            },
            {
              x: 0,
              y: 10,
              w: 4,
              h: 5,
              i: "12",
            },
            {
              x: 2,
              y: 10,
              w: 3,
              h: 5,
              i: "13",
            },
            {
              x: 4,
              y: 8,
              w: 3,
              h: 4,
              i: "14",
            },
            {
              x: 6,
              y: 10,
              w: 3,
              h: 5,
              i: "15",
            },
            {
              x: 8,
              y: 8,
              w: 1,
              h: 4,
              i: "16",
            },
            {
              x: 10,
              y: 8,
              w: 3,
              h: 4,
              i: "17",
            },
            {
              x: 0,
              y: 15,
              w: 4,
              h: 5,
              i: "18",
            },
            {
              x: 2,
              y: 12,
              w: 2,
              h: 4,
              i: "19",
            },
          ],
        },
        rowHeight: 30,
      },
      additionalProps: {},
    },
    gridProperty: {
      defaultProps: {
        isDraggable: true,
        isResizable: true,
        items: 20,
        rowHeight: 30,
        layout: {
          lg: [
            {
              w: 3,
              h: 3,
              x: 0,
              y: 0,
              i: "0",
              moved: false,
              static: false,
            },
            {
              w: 3,
              h: 3,
              x: 2,
              y: 3,
              i: "1",
              moved: false,
              static: false,
            },
            {
              w: 3,
              h: 2,
              x: 4,
              y: 6,
              i: "2",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 4,
              x: 6,
              y: 8,
              i: "3",
              moved: false,
              static: false,
            },
            {
              w: 3,
              h: 3,
              x: 8,
              y: 0,
              i: "4",
              moved: false,
              static: false,
            },
            {
              w: 3,
              h: 4,
              x: 9,
              y: 3,
              i: "5",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 5,
              x: 0,
              y: 3,
              i: "6",
              moved: false,
              static: false,
            },
            {
              w: 4,
              h: 3,
              x: 2,
              y: 8,
              i: "7",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 3,
              x: 4,
              y: 11,
              i: "8",
              moved: false,
              static: false,
            },
            {
              w: 3,
              h: 3,
              x: 6,
              y: 12,
              i: "9",
              moved: false,
              static: false,
            },
            {
              w: 1,
              h: 3,
              x: 8,
              y: 15,
              i: "10",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 3,
              x: 10,
              y: 7,
              i: "11",
              moved: false,
              static: false,
            },
            {
              w: 3,
              h: 3,
              x: 0,
              y: 11,
              i: "12",
              moved: false,
              static: false,
            },
            {
              w: 1,
              h: 4,
              x: 2,
              y: 14,
              i: "13",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 3,
              x: 4,
              y: 14,
              i: "14",
              moved: false,
              static: false,
            },
            {
              w: 1,
              h: 3,
              x: 6,
              y: 15,
              i: "15",
              moved: false,
              static: false,
            },
            {
              w: 1,
              h: 3,
              x: 8,
              y: 18,
              i: "16",
              moved: false,
              static: false,
            },
            {
              w: 1,
              h: 3,
              x: 10,
              y: 10,
              i: "17",
              moved: false,
              static: false,
            },
            {
              w: 3,
              h: 3,
              x: 0,
              y: 18,
              i: "18",
              moved: false,
              static: false,
            },
            {
              w: 3,
              h: 5,
              x: 2,
              y: 21,
              i: "19",
              moved: false,
              static: false,
            },
          ],
        },
        cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
      },
      additionalProps: {},
    },
    staticElements: {
      defaultProps: {
        cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
        layout: {
          lg: [
            {
              w: 2,
              h: 3,
              x: 0,
              y: 0,
              i: "1",
              moved: false,
              static: false,
            },
            {
              w: 4,
              h: 3,
              x: 2,
              y: 0,
              i: "2",
              moved: false,
              static: true,
            },
            {
              w: 2,
              h: 3,
              x: 6,
              y: 0,
              i: "3",
              moved: false,
              static: false,
            },
            {
              w: 4,
              h: 3,
              x: 8,
              y: 0,
              i: "4",
              moved: false,
              static: false,
            },
          ],
        },
      },
      additionalProps: {},
    },
    dynamicAddRemove: {
      defaultProps: {
        className: "layout",
        cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
        rowHeight: 100,
        layout: {
          lg: [
            {
              w: 2,
              h: 2,
              x: 0,
              y: 0,
              i: "0",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 2,
              x: 2,
              y: 0,
              i: "1",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 2,
              x: 4,
              y: 0,
              i: "2",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 2,
              x: 6,
              y: 0,
              i: "3",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 2,
              x: 8,
              y: 0,
              i: "+",
              moved: false,
              static: false,
            },
          ],
        },
      },
      additionalProps: {},
    },
    localStorage: {
      defaultProps: {
        className: "layout",
        cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
        rowHeight: 30,
        layout: {
          lg: [
            {
              w: 2,
              h: 3,
              x: 0,
              y: 0,
              i: "1",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 3,
              x: 2,
              y: 0,
              i: "2",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 3,
              x: 4,
              y: 0,
              i: "3",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 3,
              x: 6,
              y: 0,
              i: "4",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 3,
              x: 8,
              y: 0,
              i: "5",
              moved: false,
              static: false,
            },
          ],
        },
      },
      additionalProps: {},
    },
    localStorageResponsive: {
      defaultProps: {
        autoSize: true,
        className: "layout",
        cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
        rowHeight: 30,
        layout: {
          lg: [
            {
              w: 2,
              h: 3,
              x: 0,
              y: 0,
              i: "1",
              minW: 2,
              minH: 3,
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 3,
              x: 2,
              y: 0,
              i: "2",
              minW: 2,
              minH: 3,
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 3,
              x: 4,
              y: 0,
              i: "3",
              minW: 2,
              minH: 3,
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 3,
              x: 6,
              y: 0,
              i: "4",
              minW: 2,
              minH: 3,
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 3,
              x: 8,
              y: 0,
              i: "5",
              minW: 2,
              minH: 3,
              moved: false,
              static: false,
            },
          ],
        },
      },
      additionalProps: {},
    },
    minMax: {
      defaultProps: {
        isDraggable: true,
        isResizable: true,
        items: 20,
        rowHeight: 30,
        layout: {
          lg: [
            {
              w: 5,
              h: 3,
              x: 0,
              y: 0,
              i: "0",
              minW: 1,
              maxW: 5,
              minH: 2,
              maxH: 6,
              moved: false,
              static: false,
            },
            {
              w: 3,
              h: 5,
              x: 2,
              y: 3,
              i: "1",
              minW: 2,
              maxW: 6,
              minH: 5,
              maxH: 5,
              moved: false,
              static: false,
            },
            {
              w: 5,
              h: 4,
              x: 4,
              y: 8,
              i: "2",
              minW: 3,
              maxW: 6,
              minH: 4,
              maxH: 4,
              moved: false,
              static: false,
            },
            {
              w: 6,
              h: 1,
              x: 6,
              y: 0,
              i: "3",
              minW: 6,
              maxW: 6,
              minH: 1,
              maxH: 6,
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 6,
              x: 8,
              y: 12,
              i: "4",
              minW: 2,
              maxW: 4,
              minH: 6,
              maxH: 6,
              moved: false,
              static: false,
            },
            {
              w: 3,
              h: 6,
              x: 9,
              y: 18,
              i: "5",
              minW: 3,
              maxW: 3,
              minH: 6,
              maxH: 6,
              moved: false,
              static: false,
            },
            {
              w: 6,
              h: 6,
              x: 0,
              y: 34,
              i: "6",
              minW: 6,
              maxW: 6,
              minH: 6,
              maxH: 6,
              moved: false,
              static: false,
            },
            {
              w: 6,
              h: 6,
              x: 2,
              y: 40,
              i: "7",
              minW: 6,
              maxW: 6,
              minH: 6,
              maxH: 6,
              moved: false,
              static: false,
            },
            {
              w: 4,
              h: 5,
              x: 4,
              y: 29,
              i: "8",
              minW: 1,
              maxW: 4,
              minH: 5,
              maxH: 6,
              moved: false,
              static: false,
            },
            {
              w: 5,
              h: 6,
              x: 6,
              y: 49,
              i: "9",
              minW: 2,
              maxW: 6,
              minH: 5,
              maxH: 6,
              moved: false,
              static: false,
            },
            {
              w: 6,
              h: 5,
              x: 6,
              y: 34,
              i: "10",
              minW: 6,
              maxW: 6,
              minH: 4,
              maxH: 5,
              moved: false,
              static: false,
            },
            {
              w: 6,
              h: 3,
              x: 6,
              y: 24,
              i: "11",
              minW: 6,
              maxW: 6,
              minH: 1,
              maxH: 3,
              moved: false,
              static: false,
            },
            {
              w: 5,
              h: 4,
              x: 0,
              y: 49,
              i: "12",
              minW: 5,
              maxW: 5,
              minH: 3,
              maxH: 4,
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 5,
              x: 2,
              y: 8,
              i: "13",
              minW: 1,
              maxW: 3,
              minH: 4,
              maxH: 5,
              moved: false,
              static: false,
            },
            {
              w: 5,
              h: 3,
              x: 4,
              y: 46,
              i: "14",
              minW: 5,
              maxW: 5,
              minH: 2,
              maxH: 3,
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 2,
              x: 6,
              y: 27,
              i: "15",
              minW: 2,
              maxW: 4,
              minH: 2,
              maxH: 2,
              moved: false,
              static: false,
            },
            {
              w: 6,
              h: 5,
              x: 6,
              y: 59,
              i: "16",
              minW: 6,
              maxW: 6,
              minH: 5,
              maxH: 5,
              moved: false,
              static: false,
            },
            {
              w: 5,
              h: 4,
              x: 7,
              y: 55,
              i: "17",
              minW: 5,
              maxW: 5,
              minH: 3,
              maxH: 4,
              moved: false,
              static: false,
            },
            {
              w: 1,
              h: 3,
              x: 0,
              y: 3,
              i: "18",
              minW: 1,
              maxW: 2,
              minH: 2,
              maxH: 3,
              moved: false,
              static: false,
            },
            {
              w: 3,
              h: 4,
              x: 2,
              y: 13,
              i: "19",
              minW: 3,
              maxW: 4,
              minH: 4,
              maxH: 4,
              moved: false,
              static: false,
            },
          ],
        },

        cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
      },
      additionalProps: {},
    },
    dynamicMinMax: {
      defaultProps: {
        isDraggable: true,
        isResizable: true,
        items: 20,
        rowHeight: 30,
        layout: {
          lg: [
            {
              w: 2,
              h: 3,
              x: 0,
              y: 0,
              i: "0",
              moved: false,
              static: false,
            },
            {
              w: 1,
              h: 3,
              x: 2,
              y: 0,
              i: "1",
              moved: false,
              static: false,
            },
            {
              w: 1,
              h: 2,
              x: 4,
              y: 0,
              i: "2",
              moved: false,
              static: false,
            },
            {
              w: 1,
              h: 3,
              x: 6,
              y: 0,
              i: "3",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 2,
              x: 8,
              y: 0,
              i: "4",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 2,
              x: 10,
              y: 0,
              i: "5",
              moved: false,
              static: false,
            },
            {
              w: 1,
              h: 3,
              x: 0,
              y: 3,
              i: "6",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 3,
              x: 2,
              y: 3,
              i: "7",
              moved: false,
              static: false,
            },
            {
              w: 1,
              h: 3,
              x: 4,
              y: 2,
              i: "8",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 2,
              x: 6,
              y: 3,
              i: "9",
              moved: false,
              static: false,
            },
            {
              w: 1,
              h: 1,
              x: 8,
              y: 2,
              i: "10",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 3,
              x: 10,
              y: 2,
              i: "11",
              moved: false,
              static: false,
            },
            {
              w: 1,
              h: 2,
              x: 0,
              y: 6,
              i: "12",
              moved: false,
              static: false,
            },
            {
              w: 1,
              h: 1,
              x: 2,
              y: 6,
              i: "13",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 1,
              x: 4,
              y: 5,
              i: "14",
              moved: false,
              static: false,
            },
            {
              w: 1,
              h: 1,
              x: 6,
              y: 5,
              i: "15",
              moved: false,
              static: false,
            },
            {
              w: 1,
              h: 1,
              x: 8,
              y: 3,
              i: "16",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 2,
              x: 10,
              y: 5,
              i: "17",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 3,
              x: 0,
              y: 8,
              i: "18",
              moved: false,
              static: false,
            },
            {
              w: 1,
              h: 1,
              x: 2,
              y: 7,
              i: "19",
              moved: false,
              static: false,
            },
          ],
        },

        cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
      },
      additionalProps: {},
    },
    noVerticalCompact: {
      defaultProps: {
        className: "layout",
        items: 50,
        cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
        rowHeight: 30,
        layout: {
          lg: [
            {
              x: 0,
              y: 0,
              w: 2,
              h: 3,
              i: "0",
            },
            {
              x: 2,
              y: 0,
              w: 2,
              h: 4,
              i: "1",
            },
            {
              x: 4,
              y: 0,
              w: 2,
              h: 3,
              i: "2",
            },
            {
              x: 6,
              y: 0,
              w: 2,
              h: 5,
              i: "3",
            },
            {
              x: 8,
              y: 0,
              w: 2,
              h: 2,
              i: "4",
            },
            {
              x: 10,
              y: 0,
              w: 2,
              h: 4,
              i: "5",
            },
            {
              x: 0,
              y: 5,
              w: 2,
              h: 5,
              i: "6",
            },
            {
              x: 2,
              y: 4,
              w: 2,
              h: 4,
              i: "7",
            },
            {
              x: 4,
              y: 3,
              w: 2,
              h: 3,
              i: "8",
            },
            {
              x: 6,
              y: 3,
              w: 2,
              h: 3,
              i: "9",
            },
            {
              x: 8,
              y: 4,
              w: 2,
              h: 4,
              i: "10",
            },
            {
              x: 10,
              y: 3,
              w: 2,
              h: 3,
              i: "11",
            },
            {
              x: 0,
              y: 6,
              w: 2,
              h: 3,
              i: "12",
            },
            {
              x: 2,
              y: 4,
              w: 2,
              h: 2,
              i: "13",
            },
            {
              x: 4,
              y: 10,
              w: 2,
              h: 5,
              i: "14",
            },
            {
              x: 6,
              y: 6,
              w: 2,
              h: 3,
              i: "15",
            },
            {
              x: 8,
              y: 6,
              w: 2,
              h: 3,
              i: "16",
            },
            {
              x: 10,
              y: 4,
              w: 2,
              h: 2,
              i: "17",
            },
            {
              x: 0,
              y: 6,
              w: 2,
              h: 2,
              i: "18",
            },
            {
              x: 2,
              y: 9,
              w: 2,
              h: 3,
              i: "19",
            },
            {
              x: 4,
              y: 9,
              w: 2,
              h: 3,
              i: "20",
            },
            {
              x: 6,
              y: 9,
              w: 2,
              h: 3,
              i: "21",
            },
            {
              x: 8,
              y: 9,
              w: 2,
              h: 3,
              i: "22",
            },
            {
              x: 10,
              y: 9,
              w: 2,
              h: 3,
              i: "23",
            },
            {
              x: 0,
              y: 8,
              w: 2,
              h: 2,
              i: "24",
            },
            {
              x: 2,
              y: 20,
              w: 2,
              h: 5,
              i: "25",
            },
            {
              x: 4,
              y: 20,
              w: 2,
              h: 5,
              i: "26",
            },
            {
              x: 6,
              y: 20,
              w: 2,
              h: 5,
              i: "27",
            },
            {
              x: 8,
              y: 20,
              w: 2,
              h: 5,
              i: "28",
            },
            {
              x: 10,
              y: 8,
              w: 2,
              h: 2,
              i: "29",
            },
            {
              x: 0,
              y: 10,
              w: 2,
              h: 2,
              i: "30",
            },
            {
              x: 2,
              y: 15,
              w: 2,
              h: 3,
              i: "31",
            },
            {
              x: 4,
              y: 10,
              w: 2,
              h: 2,
              i: "32",
            },
            {
              x: 6,
              y: 20,
              w: 2,
              h: 4,
              i: "33",
            },
            {
              x: 8,
              y: 20,
              w: 2,
              h: 4,
              i: "34",
            },
            {
              x: 10,
              y: 25,
              w: 2,
              h: 5,
              i: "35",
            },
            {
              x: 0,
              y: 12,
              w: 2,
              h: 2,
              i: "36",
            },
            {
              x: 2,
              y: 18,
              w: 2,
              h: 3,
              i: "37",
            },
            {
              x: 4,
              y: 24,
              w: 2,
              h: 4,
              i: "38",
            },
            {
              x: 6,
              y: 24,
              w: 2,
              h: 4,
              i: "39",
            },
            {
              x: 8,
              y: 12,
              w: 2,
              h: 2,
              i: "40",
            },
            {
              x: 10,
              y: 12,
              w: 2,
              h: 2,
              i: "41",
            },
            {
              x: 0,
              y: 35,
              w: 2,
              h: 5,
              i: "42",
            },
            {
              x: 2,
              y: 28,
              w: 2,
              h: 4,
              i: "43",
            },
            {
              x: 4,
              y: 21,
              w: 2,
              h: 3,
              i: "44",
            },
            {
              x: 6,
              y: 28,
              w: 2,
              h: 4,
              i: "45",
            },
            {
              x: 8,
              y: 28,
              w: 2,
              h: 4,
              i: "46",
            },
            {
              x: 10,
              y: 14,
              w: 2,
              h: 2,
              i: "47",
            },
            {
              x: 0,
              y: 16,
              w: 2,
              h: 2,
              i: "48",
            },
            {
              x: 2,
              y: 40,
              w: 2,
              h: 5,
              i: "49",
            },
          ],
        },

        // This turns off compaction so you can place items wherever.
        verticalCompact: false,
      },
      additionalProps: {},
    },
    preventCollision: {
      defaultProps: {
        className: "layout",
        items: 50,
        cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
        rowHeight: 30,
        layout: {
          lg: [
            {
              x: 0,
              y: 0,
              w: 2,
              h: 4,
              i: "0",
            },
            {
              x: 2,
              y: 0,
              w: 2,
              h: 5,
              i: "1",
            },
            {
              x: 4,
              y: 0,
              w: 2,
              h: 5,
              i: "2",
            },
            {
              x: 6,
              y: 0,
              w: 2,
              h: 2,
              i: "3",
            },
            {
              x: 8,
              y: 0,
              w: 2,
              h: 2,
              i: "4",
            },
            {
              x: 10,
              y: 0,
              w: 2,
              h: 2,
              i: "5",
            },
            {
              x: 0,
              y: 2,
              w: 2,
              h: 2,
              i: "6",
            },
            {
              x: 2,
              y: 5,
              w: 2,
              h: 5,
              i: "7",
            },
            {
              x: 4,
              y: 4,
              w: 2,
              h: 4,
              i: "8",
            },
            {
              x: 6,
              y: 3,
              w: 2,
              h: 3,
              i: "9",
            },
            {
              x: 8,
              y: 2,
              w: 2,
              h: 2,
              i: "10",
            },
            {
              x: 10,
              y: 5,
              w: 2,
              h: 5,
              i: "11",
            },
            {
              x: 0,
              y: 10,
              w: 2,
              h: 5,
              i: "12",
            },
            {
              x: 2,
              y: 10,
              w: 2,
              h: 5,
              i: "13",
            },
            {
              x: 4,
              y: 6,
              w: 2,
              h: 3,
              i: "14",
            },
            {
              x: 6,
              y: 4,
              w: 2,
              h: 2,
              i: "15",
            },
            {
              x: 8,
              y: 4,
              w: 2,
              h: 2,
              i: "16",
            },
            {
              x: 10,
              y: 8,
              w: 2,
              h: 4,
              i: "17",
            },
            {
              x: 0,
              y: 15,
              w: 2,
              h: 5,
              i: "18",
            },
            {
              x: 2,
              y: 9,
              w: 2,
              h: 3,
              i: "19",
            },
            {
              x: 4,
              y: 9,
              w: 2,
              h: 3,
              i: "20",
            },
            {
              x: 6,
              y: 9,
              w: 2,
              h: 3,
              i: "21",
            },
            {
              x: 8,
              y: 15,
              w: 2,
              h: 5,
              i: "22",
            },
            {
              x: 10,
              y: 6,
              w: 2,
              h: 2,
              i: "23",
            },
            {
              x: 0,
              y: 8,
              w: 2,
              h: 2,
              i: "24",
            },
            {
              x: 2,
              y: 8,
              w: 2,
              h: 2,
              i: "25",
            },
            {
              x: 4,
              y: 20,
              w: 2,
              h: 5,
              i: "26",
            },
            {
              x: 6,
              y: 16,
              w: 2,
              h: 4,
              i: "27",
            },
            {
              x: 8,
              y: 16,
              w: 2,
              h: 4,
              i: "28",
            },
            {
              x: 10,
              y: 12,
              w: 2,
              h: 3,
              i: "29",
            },
            {
              x: 0,
              y: 20,
              w: 2,
              h: 4,
              i: "30",
            },
            {
              x: 2,
              y: 20,
              w: 2,
              h: 4,
              i: "31",
            },
            {
              x: 4,
              y: 20,
              w: 2,
              h: 4,
              i: "32",
            },
            {
              x: 6,
              y: 15,
              w: 2,
              h: 3,
              i: "33",
            },
            {
              x: 8,
              y: 15,
              w: 2,
              h: 3,
              i: "34",
            },
            {
              x: 10,
              y: 20,
              w: 2,
              h: 4,
              i: "35",
            },
            {
              x: 0,
              y: 12,
              w: 2,
              h: 2,
              i: "36",
            },
            {
              x: 2,
              y: 30,
              w: 2,
              h: 5,
              i: "37",
            },
            {
              x: 4,
              y: 12,
              w: 2,
              h: 2,
              i: "38",
            },
            {
              x: 6,
              y: 12,
              w: 2,
              h: 2,
              i: "39",
            },
            {
              x: 8,
              y: 18,
              w: 2,
              h: 3,
              i: "40",
            },
            {
              x: 10,
              y: 30,
              w: 2,
              h: 5,
              i: "41",
            },
            {
              x: 0,
              y: 21,
              w: 2,
              h: 3,
              i: "42",
            },
            {
              x: 2,
              y: 28,
              w: 2,
              h: 4,
              i: "43",
            },
            {
              x: 4,
              y: 21,
              w: 2,
              h: 3,
              i: "44",
            },
            {
              x: 6,
              y: 35,
              w: 2,
              h: 5,
              i: "45",
            },
            {
              x: 8,
              y: 21,
              w: 2,
              h: 3,
              i: "46",
            },
            {
              x: 10,
              y: 21,
              w: 2,
              h: 3,
              i: "47",
            },
            {
              x: 0,
              y: 40,
              w: 2,
              h: 5,
              i: "48",
            },
            {
              x: 2,
              y: 40,
              w: 2,
              h: 5,
              i: "49",
            },
          ],
        },

        // This turns off compaction so you can place items wherever.
        verticalCompact: false,
        // This turns off rearrangement so items will not be pushed arround.
        preventCollision: true,
      },
      additionalProps: {},
    },
    errorCase: {
      defaultProps: {
        className: "layout",
        items: 3,
        rowHeight: 100,
        layout: {
          lg: [
            {
              x: 0,
              y: 0,
              w: 1,
              h: 1,
              i: "1",
            },
            {
              x: 1,
              y: 0,
              w: 1,
              h: 1,
              i: "2",
            },
            {
              x: 0,
              y: 1,
              w: 2,
              h: 2,
              i: "3",
            },
          ],
        },
        cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
      },
      additionalProps: {},
    },
    toolbox: {
      defaultProps: {
        className: "layout",
        rowHeight: 30,
        layout: {
          lg: [
            {
              x: 0,
              y: 0,
              w: 1,
              h: 1,
              i: "1",
            },
            {
              x: 1,
              y: 0,
              w: 1,
              h: 1,
              i: "2",
            },
            {
              x: 0,
              y: 1,
              w: 2,
              h: 2,
              i: "3",
            },
          ],
        },

        cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
      },
      additionalProps: {},
    },
    dragFromOutside: {
      defaultProps: {
        className: "layout",
        rowHeight: 30,
        layout: {
          lg: [
            {
              w: 2,
              h: 5,
              x: 0,
              y: 0,
              i: "0",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 5,
              x: 6,
              y: 0,
              i: "1",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 2,
              x: 2,
              y: 0,
              i: "2",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 5,
              x: 4,
              y: 0,
              i: "3",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 4,
              x: 4,
              y: 0,
              i: "4",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 2,
              x: 4,
              y: 0,
              i: "5",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 5,
              x: 0,
              y: 5,
              i: "6",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 3,
              x: 2,
              y: 3,
              i: "7",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 3,
              x: 2,
              y: 3,
              i: "8",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 5,
              x: 4,
              y: 5,
              i: "9",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 5,
              x: 4,
              y: 5,
              i: "10",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 3,
              x: 4,
              y: 3,
              i: "11",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 5,
              x: 0,
              y: 10,
              i: "12",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 3,
              x: 8,
              y: 6,
              i: "13",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 2,
              x: 2,
              y: 4,
              i: "14",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 4,
              x: 4,
              y: 8,
              i: "15",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 5,
              x: 4,
              y: 10,
              i: "16",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 2,
              x: 4,
              y: 4,
              i: "17",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 2,
              x: 10,
              y: 6,
              i: "18",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 3,
              x: 4,
              y: 9,
              i: "19",
              moved: false,
              static: true,
            },
            {
              w: 2,
              h: 5,
              x: 8,
              y: 15,
              i: "20",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 2,
              x: 8,
              y: 6,
              i: "21",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 4,
              x: 4,
              y: 12,
              i: "22",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 2,
              x: 8,
              y: 6,
              i: "23",
              moved: false,
              static: false,
            },
            {
              w: 2,
              h: 4,
              x: 6,
              y: 16,
              i: "24",
              moved: false,
              static: false,
            },
          ],
        },

        cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
      },
      additionalProps: {},
    },
    bounded: {
      defaultProps: {
        className: "layout",
        items: 20,
        rowHeight: 30,
        layout: {
          lg: [
            {
              x: 0,
              y: 0,
              w: 2,
              h: 4,
              i: "0",
            },
            {
              x: 2,
              y: 0,
              w: 2,
              h: 4,
              i: "1",
            },
            {
              x: 4,
              y: 0,
              w: 2,
              h: 3,
              i: "2",
            },
            {
              x: 6,
              y: 0,
              w: 2,
              h: 4,
              i: "3",
            },
            {
              x: 8,
              y: 0,
              w: 2,
              h: 3,
              i: "4",
            },
            {
              x: 10,
              y: 0,
              w: 2,
              h: 5,
              i: "5",
            },
            {
              x: 0,
              y: 2,
              w: 2,
              h: 2,
              i: "6",
            },
            {
              x: 2,
              y: 3,
              w: 2,
              h: 3,
              i: "7",
            },
            {
              x: 4,
              y: 3,
              w: 2,
              h: 3,
              i: "8",
            },
            {
              x: 6,
              y: 4,
              w: 2,
              h: 4,
              i: "9",
            },
            {
              x: 8,
              y: 2,
              w: 2,
              h: 2,
              i: "10",
            },
            {
              x: 10,
              y: 3,
              w: 2,
              h: 3,
              i: "11",
            },
            {
              x: 0,
              y: 4,
              w: 2,
              h: 2,
              i: "12",
            },
            {
              x: 2,
              y: 8,
              w: 2,
              h: 4,
              i: "13",
            },
            {
              x: 4,
              y: 10,
              w: 2,
              h: 5,
              i: "14",
            },
            {
              x: 6,
              y: 8,
              w: 2,
              h: 4,
              i: "15",
            },
            {
              x: 8,
              y: 10,
              w: 2,
              h: 5,
              i: "16",
            },
            {
              x: 10,
              y: 6,
              w: 2,
              h: 3,
              i: "17",
            },
            {
              x: 0,
              y: 15,
              w: 2,
              h: 5,
              i: "18",
            },
            {
              x: 2,
              y: 6,
              w: 2,
              h: 2,
              i: "19",
            },
          ],
        },

        cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
      },
      additionalProps: {},
    },
    responsiveBootstrapStyle: {
      defaultProps: {
        isDraggable: true,
        isResizable: true,
        items: 20,
        rowHeight: 30,
        layout: {
          lg: [
            {
              w: 3,
              h: 4,
              x: 0,
              y: 0,
              i: "0",
              moved: false,
              static: false,
            },
            {
              w: 3,
              h: 4,
              x: 3,
              y: 0,
              i: "1",
              moved: false,
              static: false,
            },
            {
              w: 3,
              h: 4,
              x: 6,
              y: 0,
              i: "2",
              moved: false,
              static: false,
            },
            {
              w: 3,
              h: 4,
              x: 9,
              y: 0,
              i: "3",
              moved: false,
              static: false,
            },
            {
              w: 3,
              h: 4,
              x: 0,
              y: 0,
              i: "4",
              moved: false,
              static: false,
            },
            {
              w: 3,
              h: 4,
              x: 3,
              y: 0,
              i: "5",
              moved: false,
              static: false,
            },
            {
              w: 3,
              h: 4,
              x: 6,
              y: 0,
              i: "6",
              moved: false,
              static: false,
            },
            {
              w: 3,
              h: 4,
              x: 9,
              y: 0,
              i: "7",
              moved: false,
              static: false,
            },
            {
              w: 3,
              h: 4,
              x: 0,
              y: 0,
              i: "8",
              moved: false,
              static: false,
            },
            {
              w: 3,
              h: 4,
              x: 3,
              y: 0,
              i: "9",
              moved: false,
              static: false,
            },
            {
              w: 3,
              h: 4,
              x: 6,
              y: 0,
              i: "10",
              moved: false,
              static: false,
            },
            {
              w: 3,
              h: 4,
              x: 9,
              y: 0,
              i: "11",
              moved: false,
              static: false,
            },
            {
              w: 3,
              h: 4,
              x: 0,
              y: 0,
              i: "12",
              moved: false,
              static: false,
            },
            {
              w: 3,
              h: 4,
              x: 3,
              y: 0,
              i: "13",
              moved: false,
              static: false,
            },
            {
              w: 3,
              h: 4,
              x: 6,
              y: 0,
              i: "14",
              moved: false,
              static: false,
            },
            {
              w: 3,
              h: 4,
              x: 9,
              y: 0,
              i: "15",
              moved: false,
              static: false,
            },
            {
              w: 3,
              h: 4,
              x: 0,
              y: 0,
              i: "16",
              moved: false,
              static: false,
            },
            {
              w: 3,
              h: 4,
              x: 3,
              y: 0,
              i: "17",
              moved: false,
              static: false,
            },
            {
              w: 3,
              h: 4,
              x: 6,
              y: 0,
              i: "18",
              moved: false,
              static: false,
            },
            {
              w: 3,
              h: 4,
              x: 9,
              y: 0,
              i: "19",
              moved: false,
              static: false,
            },
          ],
        },

        cols: { lg: 12, md: 12, sm: 12, xs: 12, xxs: 12 },
      },
      additionalProps: {},
    },
    scale: {
      defaultProps: {
        className: "layout",
        items: 20,
        rowHeight: 30,
        layout: {
          lg: [
            {
              x: 0,
              y: 0,
              w: 2,
              h: 5,
              i: "0",
            },
            {
              x: 2,
              y: 0,
              w: 2,
              h: 5,
              i: "1",
            },
            {
              x: 4,
              y: 0,
              w: 2,
              h: 5,
              i: "2",
            },
            {
              x: 6,
              y: 0,
              w: 2,
              h: 3,
              i: "3",
            },
            {
              x: 8,
              y: 0,
              w: 2,
              h: 5,
              i: "4",
            },
            {
              x: 10,
              y: 0,
              w: 2,
              h: 5,
              i: "5",
            },
            {
              x: 0,
              y: 4,
              w: 2,
              h: 4,
              i: "6",
            },
            {
              x: 2,
              y: 3,
              w: 2,
              h: 3,
              i: "7",
            },
            {
              x: 4,
              y: 5,
              w: 2,
              h: 5,
              i: "8",
            },
            {
              x: 6,
              y: 4,
              w: 2,
              h: 4,
              i: "9",
            },
            {
              x: 8,
              y: 5,
              w: 2,
              h: 5,
              i: "10",
            },
            {
              x: 10,
              y: 5,
              w: 2,
              h: 5,
              i: "11",
            },
            {
              x: 0,
              y: 8,
              w: 2,
              h: 4,
              i: "12",
            },
            {
              x: 2,
              y: 6,
              w: 2,
              h: 3,
              i: "13",
            },
            {
              x: 4,
              y: 10,
              w: 2,
              h: 5,
              i: "14",
            },
            {
              x: 6,
              y: 4,
              w: 2,
              h: 2,
              i: "15",
            },
            {
              x: 8,
              y: 6,
              w: 2,
              h: 3,
              i: "16",
            },
            {
              x: 10,
              y: 4,
              w: 2,
              h: 2,
              i: "17",
            },
            {
              x: 0,
              y: 12,
              w: 2,
              h: 4,
              i: "18",
            },
            {
              x: 2,
              y: 6,
              w: 2,
              h: 2,
              i: "19",
            },
          ],
        },

        cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
        transformScale: 0.5,
      },
      additionalProps: {},
    },
    allowOverlap: {
      defaultProps: {
        className: "layout",
        items: 20,
        rowHeight: 30,
        layout: {
          lg: [
            {
              x: 0,
              y: 0,
              w: 2,
              h: 5,
              i: "0",
            },
            {
              x: 2,
              y: 0,
              w: 2,
              h: 3,
              i: "1",
            },
            {
              x: 4,
              y: 0,
              w: 2,
              h: 2,
              i: "2",
            },
            {
              x: 6,
              y: 0,
              w: 2,
              h: 2,
              i: "3",
            },
            {
              x: 8,
              y: 0,
              w: 2,
              h: 5,
              i: "4",
            },
            {
              x: 10,
              y: 0,
              w: 2,
              h: 3,
              i: "5",
            },
            {
              x: 0,
              y: 4,
              w: 2,
              h: 4,
              i: "6",
            },
            {
              x: 2,
              y: 2,
              w: 2,
              h: 2,
              i: "7",
            },
            {
              x: 4,
              y: 2,
              w: 2,
              h: 2,
              i: "8",
            },
            {
              x: 6,
              y: 4,
              w: 2,
              h: 4,
              i: "9",
            },
            {
              x: 8,
              y: 3,
              w: 2,
              h: 3,
              i: "10",
            },
            {
              x: 10,
              y: 2,
              w: 2,
              h: 2,
              i: "11",
            },
            {
              x: 0,
              y: 10,
              w: 2,
              h: 5,
              i: "12",
            },
            {
              x: 2,
              y: 8,
              w: 2,
              h: 4,
              i: "13",
            },
            {
              x: 4,
              y: 6,
              w: 2,
              h: 3,
              i: "14",
            },
            {
              x: 6,
              y: 6,
              w: 2,
              h: 3,
              i: "15",
            },
            {
              x: 8,
              y: 10,
              w: 2,
              h: 5,
              i: "16",
            },
            {
              x: 10,
              y: 4,
              w: 2,
              h: 2,
              i: "17",
            },
            {
              x: 0,
              y: 12,
              w: 2,
              h: 4,
              i: "18",
            },
            {
              x: 2,
              y: 15,
              w: 2,
              h: 5,
              i: "19",
            },
          ],
        },

        cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
      },
      additionalProps: {},
    },
    resizableHandles: {
      defaultProps: {
        className: "layout",
        items: 20,
        rowHeight: 30,
        layout: {
          lg: [
            {
              x: 0,
              y: 0,
              w: 2,
              h: 5,
              i: "0",
              resizeHandles: ["s", "w", "e", "n", "sw", "nw", "se", "ne"],
            },
            {
              x: 2,
              y: 0,
              w: 2,
              h: 3,
              i: "1",
            },
            {
              x: 4,
              y: 0,
              w: 2,
              h: 5,
              i: "2",
            },
            {
              x: 6,
              y: 0,
              w: 2,
              h: 2,
              i: "3",
            },
            {
              x: 8,
              y: 0,
              w: 2,
              h: 5,
              i: "4",
            },
            {
              x: 10,
              y: 0,
              w: 2,
              h: 4,
              i: "5",
            },
            {
              x: 0,
              y: 5,
              w: 2,
              h: 5,
              i: "6",
            },
            {
              x: 2,
              y: 2,
              w: 2,
              h: 2,
              i: "7",
            },
            {
              x: 4,
              y: 4,
              w: 2,
              h: 4,
              i: "8",
            },
            {
              x: 6,
              y: 5,
              w: 2,
              h: 5,
              i: "9",
            },
            {
              x: 8,
              y: 4,
              w: 2,
              h: 4,
              i: "10",
            },
            {
              x: 10,
              y: 4,
              w: 2,
              h: 4,
              i: "11",
            },
            {
              x: 0,
              y: 6,
              w: 2,
              h: 3,
              i: "12",
            },
            {
              x: 2,
              y: 8,
              w: 2,
              h: 4,
              i: "13",
            },
            {
              x: 4,
              y: 4,
              w: 2,
              h: 2,
              i: "14",
            },
            {
              x: 6,
              y: 8,
              w: 2,
              h: 4,
              i: "15",
            },
            {
              x: 8,
              y: 4,
              w: 2,
              h: 2,
              i: "16",
            },
            {
              x: 10,
              y: 6,
              w: 2,
              h: 3,
              i: "17",
            },
            {
              x: 0,
              y: 6,
              w: 2,
              h: 2,
              i: "18",
            },
            {
              x: 2,
              y: 6,
              w: 2,
              h: 2,
              i: "19",
            },
          ],
        },

        cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
      },
      additionalProps: {},
    },
    horizontal: {
      defaultProps: {
        className: "layout",
        items: 5,
        rowHeight: 5,

        cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
        compactType: "horizontal",
        maxRows: 1,
        allowOverlap: false,
        layout: {
          lg: [
            {
              x: 0,
              y: 0,
              w: 2,
              h: 5,
              i: "0",
            },
            {
              x: 2,
              y: 0,
              w: 2,
              h: 5,
              i: "1",
            },
            {
              x: 4,
              y: 0,
              w: 2,
              h: 5,
              i: "2",
            },
            {
              x: 6,
              y: 0,
              w: 2,
              h: 5,
              i: "3",
            },
            {
              x: 8,
              y: 0,
              w: 2,
              h: 5,
              i: "4",
            },
          ],
        },
      },
      additionalProps: {},
    },
  }
}
