import omit from "lodash/omit";

export const data: any = {
  empty: {
    defaultProps: {},
    additionalProps: {
      disabled: true,
    },
  },
  showcase: {
    defaultProps: {
      className: "layout",
      rowHeight: 30,
      cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
      layout: {
        lg: [
          {
            w: 2,
            h: 2,
            minH: 2,
            minW: 2,
            x: 2,
            y: 0,
            i: "0",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 5,
            x: 2,
            y: 0,
            i: "1",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 2,
            x: 8,
            y: 0,
            i: "2",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 3,
            x: 2,
            y: 0,
            i: "3",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 3,
            x: 4,
            y: 0,
            i: "4",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 5,
            x: 8,
            y: 0,
            i: "5",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 4,
            x: 2,
            y: 4,
            i: "6",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 5,
            x: 10,
            y: 5,
            i: "7",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 5,
            x: 4,
            y: 5,
            i: "8",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 3,
            x: 8,
            y: 3,
            i: "9",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 4,
            x: 6,
            y: 4,
            i: "10",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 2,
            x: 4,
            y: 2,
            i: "11",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 4,
            x: 2,
            y: 8,
            i: "12",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 3,
            x: 8,
            y: 6,
            i: "13",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 2,
            x: 2,
            y: 4,
            i: "14",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 3,
            x: 8,
            y: 6,
            i: "15",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 4,
            x: 4,
            y: 8,
            i: "16",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 4,
            x: 6,
            y: 8,
            i: "17",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 3,
            x: 6,
            y: 9,
            i: "18",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 2,
            x: 2,
            y: 6,
            i: "19",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 3,
            x: 8,
            y: 9,
            i: "20",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 4,
            x: 4,
            y: 12,
            i: "21",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 3,
            x: 6,
            y: 9,
            i: "22",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 3,
            x: 6,
            y: 9,
            i: "23",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 3,
            x: 8,
            y: 12,
            i: "24",
            static: false,
            resizeHandles: ["se"],
          },
        ],
      },
    },
    additionalProps: {
      responsive: true,
    },
    state: {
      currentBreakpoint: "lg",
      compactType: "vertical",
      resizeHandles: ["se"],
      mounted: false,
      layouts: {
        lg: [
          {
            w: 2,
            h: 2,
            x: 2,
            y: 0,
            i: "0",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 5,
            x: 2,
            y: 0,
            i: "1",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 2,
            x: 8,
            y: 0,
            i: "2",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 3,
            x: 2,
            y: 0,
            i: "3",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 3,
            x: 4,
            y: 0,
            i: "4",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 5,
            x: 8,
            y: 0,
            i: "5",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 4,
            x: 2,
            y: 4,
            i: "6",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 5,
            x: 10,
            y: 5,
            i: "7",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 5,
            x: 4,
            y: 5,
            i: "8",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 3,
            x: 8,
            y: 3,
            i: "9",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 4,
            x: 6,
            y: 4,
            i: "10",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 2,
            x: 4,
            y: 2,
            i: "11",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 4,
            x: 2,
            y: 8,
            i: "12",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 3,
            x: 8,
            y: 6,
            i: "13",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 2,
            x: 2,
            y: 4,
            i: "14",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 3,
            x: 8,
            y: 6,
            i: "15",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 4,
            x: 4,
            y: 8,
            i: "16",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 4,
            x: 6,
            y: 8,
            i: "17",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 3,
            x: 6,
            y: 9,
            i: "18",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 2,
            x: 2,
            y: 6,
            i: "19",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 3,
            x: 8,
            y: 9,
            i: "20",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 4,
            x: 4,
            y: 12,
            i: "21",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 3,
            x: 6,
            y: 9,
            i: "22",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 3,
            x: 6,
            y: 9,
            i: "23",
            static: false,
            resizeHandles: ["se"],
          },
          {
            w: 2,
            h: 3,
            x: 8,
            y: 12,
            i: "24",
            static: false,
            resizeHandles: ["se"],
          },
        ],
      },
    },
  },
  basic: {
    defaultProps: {
      className: "layout",
      items: 5,
      rowHeight: 30,
      cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
      layout: {
        lg: [
          {
            x: 0,
            y: 0,
            w: 2,
            h: 3,
            i: "0",
          },
          {
            x: 2,
            y: 0,
            w: 2,
            h: 2,
            i: "1",
          },
          {
            x: 4,
            y: 0,
            w: 2,
            h: 4,
            i: "2",
          },
          {
            x: 6,
            y: 0,
            w: 2,
            h: 4,
            i: "3",
          },
          {
            x: 8,
            y: 0,
            w: 2,
            h: 4,
            i: "4",
          },
        ],
      },
    },
    additionalProps: {
      responsive: true,
    },
  },
  noDragging: {
    defaultProps: {
      className: "layout",
      isDraggable: false,
      isResizable: false,
      items: 50,
      cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
      rowHeight: 30,
      layout: {
        lg: [
          {
            x: 0,
            y: 0,
            w: 2,
            h: 5,
            i: "0",
          },
          {
            x: 2,
            y: 0,
            w: 2,
            h: 5,
            i: "1",
          },
          {
            x: 4,
            y: 0,
            w: 2,
            h: 2,
            i: "2",
          },
          {
            x: 6,
            y: 0,
            w: 2,
            h: 3,
            i: "3",
          },
          {
            x: 8,
            y: 0,
            w: 2,
            h: 3,
            i: "4",
          },
          {
            x: 10,
            y: 0,
            w: 2,
            h: 4,
            i: "5",
          },
          {
            x: 0,
            y: 3,
            w: 2,
            h: 3,
            i: "6",
          },
          {
            x: 2,
            y: 3,
            w: 2,
            h: 3,
            i: "7",
          },
          {
            x: 4,
            y: 5,
            w: 2,
            h: 5,
            i: "8",
          },
          {
            x: 6,
            y: 5,
            w: 2,
            h: 5,
            i: "9",
          },
          {
            x: 8,
            y: 5,
            w: 2,
            h: 5,
            i: "10",
          },
          {
            x: 10,
            y: 5,
            w: 2,
            h: 5,
            i: "11",
          },
          {
            x: 0,
            y: 10,
            w: 2,
            h: 5,
            i: "12",
          },
          {
            x: 2,
            y: 10,
            w: 2,
            h: 5,
            i: "13",
          },
          {
            x: 4,
            y: 6,
            w: 2,
            h: 3,
            i: "14",
          },
          {
            x: 6,
            y: 6,
            w: 2,
            h: 3,
            i: "15",
          },
          {
            x: 8,
            y: 6,
            w: 2,
            h: 3,
            i: "16",
          },
          {
            x: 10,
            y: 8,
            w: 2,
            h: 4,
            i: "17",
          },
          {
            x: 0,
            y: 12,
            w: 2,
            h: 4,
            i: "18",
          },
          {
            x: 2,
            y: 9,
            w: 2,
            h: 3,
            i: "19",
          },
          {
            x: 4,
            y: 9,
            w: 2,
            h: 3,
            i: "20",
          },
          {
            x: 6,
            y: 9,
            w: 2,
            h: 3,
            i: "21",
          },
          {
            x: 8,
            y: 6,
            w: 2,
            h: 2,
            i: "22",
          },
          {
            x: 10,
            y: 9,
            w: 2,
            h: 3,
            i: "23",
          },
          {
            x: 0,
            y: 8,
            w: 2,
            h: 2,
            i: "24",
          },
          {
            x: 2,
            y: 20,
            w: 2,
            h: 5,
            i: "25",
          },
          {
            x: 4,
            y: 8,
            w: 2,
            h: 2,
            i: "26",
          },
          {
            x: 6,
            y: 16,
            w: 2,
            h: 4,
            i: "27",
          },
          {
            x: 8,
            y: 8,
            w: 2,
            h: 2,
            i: "28",
          },
          {
            x: 10,
            y: 20,
            w: 2,
            h: 5,
            i: "29",
          },
          {
            x: 0,
            y: 20,
            w: 2,
            h: 4,
            i: "30",
          },
          {
            x: 2,
            y: 20,
            w: 2,
            h: 4,
            i: "31",
          },
          {
            x: 4,
            y: 20,
            w: 2,
            h: 4,
            i: "32",
          },
          {
            x: 6,
            y: 25,
            w: 2,
            h: 5,
            i: "33",
          },
          {
            x: 8,
            y: 10,
            w: 2,
            h: 2,
            i: "34",
          },
          {
            x: 10,
            y: 10,
            w: 2,
            h: 2,
            i: "35",
          },
          {
            x: 0,
            y: 30,
            w: 2,
            h: 5,
            i: "36",
          },
          {
            x: 2,
            y: 18,
            w: 2,
            h: 3,
            i: "37",
          },
          {
            x: 4,
            y: 12,
            w: 2,
            h: 2,
            i: "38",
          },
          {
            x: 6,
            y: 12,
            w: 2,
            h: 2,
            i: "39",
          },
          {
            x: 8,
            y: 24,
            w: 2,
            h: 4,
            i: "40",
          },
          {
            x: 10,
            y: 30,
            w: 2,
            h: 5,
            i: "41",
          },
          {
            x: 0,
            y: 14,
            w: 2,
            h: 2,
            i: "42",
          },
          {
            x: 2,
            y: 35,
            w: 2,
            h: 5,
            i: "43",
          },
          {
            x: 4,
            y: 21,
            w: 2,
            h: 3,
            i: "44",
          },
          {
            x: 6,
            y: 35,
            w: 2,
            h: 5,
            i: "45",
          },
          {
            x: 8,
            y: 14,
            w: 2,
            h: 2,
            i: "46",
          },
          {
            x: 10,
            y: 14,
            w: 2,
            h: 2,
            i: "47",
          },
          {
            x: 0,
            y: 40,
            w: 2,
            h: 5,
            i: "48",
          },
          {
            x: 2,
            y: 32,
            w: 2,
            h: 4,
            i: "49",
          },
        ],
      },
    },
    additionalProps: {},
  },
  messy: {
    defaultProps: {
      className: "layout",
      cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
      items: 20,
      layout: {
        lg: [
          {
            x: 0,
            y: 0,
            w: 1,
            h: 5,
            i: "0",
          },
          {
            x: 2,
            y: 0,
            w: 2,
            h: 2,
            i: "1",
          },
          {
            x: 4,
            y: 0,
            w: 1,
            h: 4,
            i: "2",
          },
          {
            x: 6,
            y: 0,
            w: 3,
            h: 3,
            i: "3",
          },
          {
            x: 8,
            y: 0,
            w: 3,
            h: 4,
            i: "4",
          },
          {
            x: 10,
            y: 0,
            w: 1,
            h: 2,
            i: "5",
          },
          {
            x: 0,
            y: 2,
            w: 4,
            h: 2,
            i: "6",
          },
          {
            x: 2,
            y: 4,
            w: 3,
            h: 4,
            i: "7",
          },
          {
            x: 4,
            y: 4,
            w: 2,
            h: 4,
            i: "8",
          },
          {
            x: 6,
            y: 2,
            w: 2,
            h: 2,
            i: "9",
          },
          {
            x: 8,
            y: 3,
            w: 2,
            h: 3,
            i: "10",
          },
          {
            x: 10,
            y: 2,
            w: 4,
            h: 2,
            i: "11",
          },
          {
            x: 0,
            y: 10,
            w: 4,
            h: 5,
            i: "12",
          },
          {
            x: 2,
            y: 10,
            w: 3,
            h: 5,
            i: "13",
          },
          {
            x: 4,
            y: 8,
            w: 3,
            h: 4,
            i: "14",
          },
          {
            x: 6,
            y: 10,
            w: 3,
            h: 5,
            i: "15",
          },
          {
            x: 8,
            y: 8,
            w: 1,
            h: 4,
            i: "16",
          },
          {
            x: 10,
            y: 8,
            w: 3,
            h: 4,
            i: "17",
          },
          {
            x: 0,
            y: 15,
            w: 4,
            h: 5,
            i: "18",
          },
          {
            x: 2,
            y: 12,
            w: 2,
            h: 4,
            i: "19",
          },
        ],
      },
      rowHeight: 30,
    },
    additionalProps: {},
  },
  gridProperty: {
    defaultProps: {
      isDraggable: true,
      isResizable: true,
      items: 20,
      rowHeight: 30,
      layout: {
        lg: [
          {
            w: 3,
            h: 3,
            x: 0,
            y: 0,
            i: "0",
            moved: false,
            static: false,
          },
          {
            w: 3,
            h: 3,
            x: 2,
            y: 3,
            i: "1",
            moved: false,
            static: false,
          },
          {
            w: 3,
            h: 2,
            x: 4,
            y: 6,
            i: "2",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 4,
            x: 6,
            y: 8,
            i: "3",
            moved: false,
            static: false,
          },
          {
            w: 3,
            h: 3,
            x: 8,
            y: 0,
            i: "4",
            moved: false,
            static: false,
          },
          {
            w: 3,
            h: 4,
            x: 9,
            y: 3,
            i: "5",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 5,
            x: 0,
            y: 3,
            i: "6",
            moved: false,
            static: false,
          },
          {
            w: 4,
            h: 3,
            x: 2,
            y: 8,
            i: "7",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 3,
            x: 4,
            y: 11,
            i: "8",
            moved: false,
            static: false,
          },
          {
            w: 3,
            h: 3,
            x: 6,
            y: 12,
            i: "9",
            moved: false,
            static: false,
          },
          {
            w: 1,
            h: 3,
            x: 8,
            y: 15,
            i: "10",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 3,
            x: 10,
            y: 7,
            i: "11",
            moved: false,
            static: false,
          },
          {
            w: 3,
            h: 3,
            x: 0,
            y: 11,
            i: "12",
            moved: false,
            static: false,
          },
          {
            w: 1,
            h: 4,
            x: 2,
            y: 14,
            i: "13",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 3,
            x: 4,
            y: 14,
            i: "14",
            moved: false,
            static: false,
          },
          {
            w: 1,
            h: 3,
            x: 6,
            y: 15,
            i: "15",
            moved: false,
            static: false,
          },
          {
            w: 1,
            h: 3,
            x: 8,
            y: 18,
            i: "16",
            moved: false,
            static: false,
          },
          {
            w: 1,
            h: 3,
            x: 10,
            y: 10,
            i: "17",
            moved: false,
            static: false,
          },
          {
            w: 3,
            h: 3,
            x: 0,
            y: 18,
            i: "18",
            moved: false,
            static: false,
          },
          {
            w: 3,
            h: 5,
            x: 2,
            y: 21,
            i: "19",
            moved: false,
            static: false,
          },
        ],
      },
      cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
    },
    additionalProps: {},
  },
  staticElements: {
    defaultProps: {
      cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
      layout: {
        lg: [
          {
            w: 2,
            h: 3,
            x: 0,
            y: 0,
            i: "1",
            moved: false,
            static: false,
          },
          {
            w: 4,
            h: 3,
            x: 2,
            y: 0,
            i: "2",
            moved: false,
            static: true,
          },
          {
            w: 2,
            h: 3,
            x: 6,
            y: 0,
            i: "3",
            moved: false,
            static: false,
          },
          {
            w: 4,
            h: 3,
            x: 8,
            y: 0,
            i: "4",
            moved: false,
            static: false,
          },
        ],
      },
    },
    additionalProps: {},
  },
  dynamicAddRemove: {
    defaultProps: {
      className: "layout",
      cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
      rowHeight: 100,
      layout: {
        lg: [
          {
            w: 2,
            h: 2,
            x: 0,
            y: 0,
            i: "0",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 2,
            x: 2,
            y: 0,
            i: "1",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 2,
            x: 4,
            y: 0,
            i: "2",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 2,
            x: 6,
            y: 0,
            i: "3",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 2,
            x: 8,
            y: 0,
            i: "+",
            moved: false,
            static: false,
          },
        ],
      },
    },
    additionalProps: {},
  },
  localStorage: {
    defaultProps: {
      className: "layout",
      cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
      rowHeight: 30,
      layout: {
        lg: [
          {
            w: 2,
            h: 3,
            x: 0,
            y: 0,
            i: "1",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 3,
            x: 2,
            y: 0,
            i: "2",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 3,
            x: 4,
            y: 0,
            i: "3",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 3,
            x: 6,
            y: 0,
            i: "4",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 3,
            x: 8,
            y: 0,
            i: "5",
            moved: false,
            static: false,
          },
        ],
      },
    },
    additionalProps: {},
  },
  localStorageResponsive: {
    defaultProps: {
      autoSize: true,
      className: "layout",
      cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
      rowHeight: 30,
      layout: {
        lg: [
          {
            w: 2,
            h: 3,
            x: 0,
            y: 0,
            i: "1",
            minW: 2,
            minH: 3,
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 3,
            x: 2,
            y: 0,
            i: "2",
            minW: 2,
            minH: 3,
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 3,
            x: 4,
            y: 0,
            i: "3",
            minW: 2,
            minH: 3,
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 3,
            x: 6,
            y: 0,
            i: "4",
            minW: 2,
            minH: 3,
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 3,
            x: 8,
            y: 0,
            i: "5",
            minW: 2,
            minH: 3,
            moved: false,
            static: false,
          },
        ],
      },
    },
    additionalProps: {},
  },
  minMax: {
    defaultProps: {
      isDraggable: true,
      isResizable: true,
      items: 20,
      rowHeight: 30,
      layout: {
        lg: [
          {
            w: 5,
            h: 3,
            x: 0,
            y: 0,
            i: "0",
            minW: 1,
            maxW: 5,
            minH: 2,
            maxH: 6,
            moved: false,
            static: false,
          },
          {
            w: 3,
            h: 5,
            x: 2,
            y: 3,
            i: "1",
            minW: 2,
            maxW: 6,
            minH: 5,
            maxH: 5,
            moved: false,
            static: false,
          },
          {
            w: 5,
            h: 4,
            x: 4,
            y: 8,
            i: "2",
            minW: 3,
            maxW: 6,
            minH: 4,
            maxH: 4,
            moved: false,
            static: false,
          },
          {
            w: 6,
            h: 1,
            x: 6,
            y: 0,
            i: "3",
            minW: 6,
            maxW: 6,
            minH: 1,
            maxH: 6,
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 6,
            x: 8,
            y: 12,
            i: "4",
            minW: 2,
            maxW: 4,
            minH: 6,
            maxH: 6,
            moved: false,
            static: false,
          },
          {
            w: 3,
            h: 6,
            x: 9,
            y: 18,
            i: "5",
            minW: 3,
            maxW: 3,
            minH: 6,
            maxH: 6,
            moved: false,
            static: false,
          },
          {
            w: 6,
            h: 6,
            x: 0,
            y: 34,
            i: "6",
            minW: 6,
            maxW: 6,
            minH: 6,
            maxH: 6,
            moved: false,
            static: false,
          },
          {
            w: 6,
            h: 6,
            x: 2,
            y: 40,
            i: "7",
            minW: 6,
            maxW: 6,
            minH: 6,
            maxH: 6,
            moved: false,
            static: false,
          },
          {
            w: 4,
            h: 5,
            x: 4,
            y: 29,
            i: "8",
            minW: 1,
            maxW: 4,
            minH: 5,
            maxH: 6,
            moved: false,
            static: false,
          },
          {
            w: 5,
            h: 6,
            x: 6,
            y: 49,
            i: "9",
            minW: 2,
            maxW: 6,
            minH: 5,
            maxH: 6,
            moved: false,
            static: false,
          },
          {
            w: 6,
            h: 5,
            x: 6,
            y: 34,
            i: "10",
            minW: 6,
            maxW: 6,
            minH: 4,
            maxH: 5,
            moved: false,
            static: false,
          },
          {
            w: 6,
            h: 3,
            x: 6,
            y: 24,
            i: "11",
            minW: 6,
            maxW: 6,
            minH: 1,
            maxH: 3,
            moved: false,
            static: false,
          },
          {
            w: 5,
            h: 4,
            x: 0,
            y: 49,
            i: "12",
            minW: 5,
            maxW: 5,
            minH: 3,
            maxH: 4,
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 5,
            x: 2,
            y: 8,
            i: "13",
            minW: 1,
            maxW: 3,
            minH: 4,
            maxH: 5,
            moved: false,
            static: false,
          },
          {
            w: 5,
            h: 3,
            x: 4,
            y: 46,
            i: "14",
            minW: 5,
            maxW: 5,
            minH: 2,
            maxH: 3,
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 2,
            x: 6,
            y: 27,
            i: "15",
            minW: 2,
            maxW: 4,
            minH: 2,
            maxH: 2,
            moved: false,
            static: false,
          },
          {
            w: 6,
            h: 5,
            x: 6,
            y: 59,
            i: "16",
            minW: 6,
            maxW: 6,
            minH: 5,
            maxH: 5,
            moved: false,
            static: false,
          },
          {
            w: 5,
            h: 4,
            x: 7,
            y: 55,
            i: "17",
            minW: 5,
            maxW: 5,
            minH: 3,
            maxH: 4,
            moved: false,
            static: false,
          },
          {
            w: 1,
            h: 3,
            x: 0,
            y: 3,
            i: "18",
            minW: 1,
            maxW: 2,
            minH: 2,
            maxH: 3,
            moved: false,
            static: false,
          },
          {
            w: 3,
            h: 4,
            x: 2,
            y: 13,
            i: "19",
            minW: 3,
            maxW: 4,
            minH: 4,
            maxH: 4,
            moved: false,
            static: false,
          },
        ],
      },

      cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
    },
    additionalProps: {},
  },
  dynamicMinMax: {
    defaultProps: {
      isDraggable: true,
      isResizable: true,
      items: 20,
      rowHeight: 30,
      layout: {
        lg: [
          {
            w: 2,
            h: 3,
            x: 0,
            y: 0,
            i: "0",
            moved: false,
            static: false,
          },
          {
            w: 1,
            h: 3,
            x: 2,
            y: 0,
            i: "1",
            moved: false,
            static: false,
          },
          {
            w: 1,
            h: 2,
            x: 4,
            y: 0,
            i: "2",
            moved: false,
            static: false,
          },
          {
            w: 1,
            h: 3,
            x: 6,
            y: 0,
            i: "3",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 2,
            x: 8,
            y: 0,
            i: "4",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 2,
            x: 10,
            y: 0,
            i: "5",
            moved: false,
            static: false,
          },
          {
            w: 1,
            h: 3,
            x: 0,
            y: 3,
            i: "6",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 3,
            x: 2,
            y: 3,
            i: "7",
            moved: false,
            static: false,
          },
          {
            w: 1,
            h: 3,
            x: 4,
            y: 2,
            i: "8",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 2,
            x: 6,
            y: 3,
            i: "9",
            moved: false,
            static: false,
          },
          {
            w: 1,
            h: 1,
            x: 8,
            y: 2,
            i: "10",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 3,
            x: 10,
            y: 2,
            i: "11",
            moved: false,
            static: false,
          },
          {
            w: 1,
            h: 2,
            x: 0,
            y: 6,
            i: "12",
            moved: false,
            static: false,
          },
          {
            w: 1,
            h: 1,
            x: 2,
            y: 6,
            i: "13",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 1,
            x: 4,
            y: 5,
            i: "14",
            moved: false,
            static: false,
          },
          {
            w: 1,
            h: 1,
            x: 6,
            y: 5,
            i: "15",
            moved: false,
            static: false,
          },
          {
            w: 1,
            h: 1,
            x: 8,
            y: 3,
            i: "16",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 2,
            x: 10,
            y: 5,
            i: "17",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 3,
            x: 0,
            y: 8,
            i: "18",
            moved: false,
            static: false,
          },
          {
            w: 1,
            h: 1,
            x: 2,
            y: 7,
            i: "19",
            moved: false,
            static: false,
          },
        ],
      },

      cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
    },
    additionalProps: {},
  },
  noVerticalCompact: {
    defaultProps: {
      className: "layout",
      items: 50,
      cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
      rowHeight: 30,
      layout: {
        lg: [
          {
            x: 0,
            y: 0,
            w: 2,
            h: 3,
            i: "0",
          },
          {
            x: 2,
            y: 0,
            w: 2,
            h: 4,
            i: "1",
          },
          {
            x: 4,
            y: 0,
            w: 2,
            h: 3,
            i: "2",
          },
          {
            x: 6,
            y: 0,
            w: 2,
            h: 5,
            i: "3",
          },
          {
            x: 8,
            y: 0,
            w: 2,
            h: 2,
            i: "4",
          },
          {
            x: 10,
            y: 0,
            w: 2,
            h: 4,
            i: "5",
          },
          {
            x: 0,
            y: 5,
            w: 2,
            h: 5,
            i: "6",
          },
          {
            x: 2,
            y: 4,
            w: 2,
            h: 4,
            i: "7",
          },
          {
            x: 4,
            y: 3,
            w: 2,
            h: 3,
            i: "8",
          },
          {
            x: 6,
            y: 3,
            w: 2,
            h: 3,
            i: "9",
          },
          {
            x: 8,
            y: 4,
            w: 2,
            h: 4,
            i: "10",
          },
          {
            x: 10,
            y: 3,
            w: 2,
            h: 3,
            i: "11",
          },
          {
            x: 0,
            y: 6,
            w: 2,
            h: 3,
            i: "12",
          },
          {
            x: 2,
            y: 4,
            w: 2,
            h: 2,
            i: "13",
          },
          {
            x: 4,
            y: 10,
            w: 2,
            h: 5,
            i: "14",
          },
          {
            x: 6,
            y: 6,
            w: 2,
            h: 3,
            i: "15",
          },
          {
            x: 8,
            y: 6,
            w: 2,
            h: 3,
            i: "16",
          },
          {
            x: 10,
            y: 4,
            w: 2,
            h: 2,
            i: "17",
          },
          {
            x: 0,
            y: 6,
            w: 2,
            h: 2,
            i: "18",
          },
          {
            x: 2,
            y: 9,
            w: 2,
            h: 3,
            i: "19",
          },
          {
            x: 4,
            y: 9,
            w: 2,
            h: 3,
            i: "20",
          },
          {
            x: 6,
            y: 9,
            w: 2,
            h: 3,
            i: "21",
          },
          {
            x: 8,
            y: 9,
            w: 2,
            h: 3,
            i: "22",
          },
          {
            x: 10,
            y: 9,
            w: 2,
            h: 3,
            i: "23",
          },
          {
            x: 0,
            y: 8,
            w: 2,
            h: 2,
            i: "24",
          },
          {
            x: 2,
            y: 20,
            w: 2,
            h: 5,
            i: "25",
          },
          {
            x: 4,
            y: 20,
            w: 2,
            h: 5,
            i: "26",
          },
          {
            x: 6,
            y: 20,
            w: 2,
            h: 5,
            i: "27",
          },
          {
            x: 8,
            y: 20,
            w: 2,
            h: 5,
            i: "28",
          },
          {
            x: 10,
            y: 8,
            w: 2,
            h: 2,
            i: "29",
          },
          {
            x: 0,
            y: 10,
            w: 2,
            h: 2,
            i: "30",
          },
          {
            x: 2,
            y: 15,
            w: 2,
            h: 3,
            i: "31",
          },
          {
            x: 4,
            y: 10,
            w: 2,
            h: 2,
            i: "32",
          },
          {
            x: 6,
            y: 20,
            w: 2,
            h: 4,
            i: "33",
          },
          {
            x: 8,
            y: 20,
            w: 2,
            h: 4,
            i: "34",
          },
          {
            x: 10,
            y: 25,
            w: 2,
            h: 5,
            i: "35",
          },
          {
            x: 0,
            y: 12,
            w: 2,
            h: 2,
            i: "36",
          },
          {
            x: 2,
            y: 18,
            w: 2,
            h: 3,
            i: "37",
          },
          {
            x: 4,
            y: 24,
            w: 2,
            h: 4,
            i: "38",
          },
          {
            x: 6,
            y: 24,
            w: 2,
            h: 4,
            i: "39",
          },
          {
            x: 8,
            y: 12,
            w: 2,
            h: 2,
            i: "40",
          },
          {
            x: 10,
            y: 12,
            w: 2,
            h: 2,
            i: "41",
          },
          {
            x: 0,
            y: 35,
            w: 2,
            h: 5,
            i: "42",
          },
          {
            x: 2,
            y: 28,
            w: 2,
            h: 4,
            i: "43",
          },
          {
            x: 4,
            y: 21,
            w: 2,
            h: 3,
            i: "44",
          },
          {
            x: 6,
            y: 28,
            w: 2,
            h: 4,
            i: "45",
          },
          {
            x: 8,
            y: 28,
            w: 2,
            h: 4,
            i: "46",
          },
          {
            x: 10,
            y: 14,
            w: 2,
            h: 2,
            i: "47",
          },
          {
            x: 0,
            y: 16,
            w: 2,
            h: 2,
            i: "48",
          },
          {
            x: 2,
            y: 40,
            w: 2,
            h: 5,
            i: "49",
          },
        ],
      },

      // This turns off compaction so you can place items wherever.
      verticalCompact: false,
    },
    additionalProps: {},
  },
  preventCollision: {
    defaultProps: {
      className: "layout",
      items: 50,
      cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
      rowHeight: 30,
      layout: {
        lg: [
          {
            x: 0,
            y: 0,
            w: 2,
            h: 4,
            i: "0",
          },
          {
            x: 2,
            y: 0,
            w: 2,
            h: 5,
            i: "1",
          },
          {
            x: 4,
            y: 0,
            w: 2,
            h: 5,
            i: "2",
          },
          {
            x: 6,
            y: 0,
            w: 2,
            h: 2,
            i: "3",
          },
          {
            x: 8,
            y: 0,
            w: 2,
            h: 2,
            i: "4",
          },
          {
            x: 10,
            y: 0,
            w: 2,
            h: 2,
            i: "5",
          },
          {
            x: 0,
            y: 2,
            w: 2,
            h: 2,
            i: "6",
          },
          {
            x: 2,
            y: 5,
            w: 2,
            h: 5,
            i: "7",
          },
          {
            x: 4,
            y: 4,
            w: 2,
            h: 4,
            i: "8",
          },
          {
            x: 6,
            y: 3,
            w: 2,
            h: 3,
            i: "9",
          },
          {
            x: 8,
            y: 2,
            w: 2,
            h: 2,
            i: "10",
          },
          {
            x: 10,
            y: 5,
            w: 2,
            h: 5,
            i: "11",
          },
          {
            x: 0,
            y: 10,
            w: 2,
            h: 5,
            i: "12",
          },
          {
            x: 2,
            y: 10,
            w: 2,
            h: 5,
            i: "13",
          },
          {
            x: 4,
            y: 6,
            w: 2,
            h: 3,
            i: "14",
          },
          {
            x: 6,
            y: 4,
            w: 2,
            h: 2,
            i: "15",
          },
          {
            x: 8,
            y: 4,
            w: 2,
            h: 2,
            i: "16",
          },
          {
            x: 10,
            y: 8,
            w: 2,
            h: 4,
            i: "17",
          },
          {
            x: 0,
            y: 15,
            w: 2,
            h: 5,
            i: "18",
          },
          {
            x: 2,
            y: 9,
            w: 2,
            h: 3,
            i: "19",
          },
          {
            x: 4,
            y: 9,
            w: 2,
            h: 3,
            i: "20",
          },
          {
            x: 6,
            y: 9,
            w: 2,
            h: 3,
            i: "21",
          },
          {
            x: 8,
            y: 15,
            w: 2,
            h: 5,
            i: "22",
          },
          {
            x: 10,
            y: 6,
            w: 2,
            h: 2,
            i: "23",
          },
          {
            x: 0,
            y: 8,
            w: 2,
            h: 2,
            i: "24",
          },
          {
            x: 2,
            y: 8,
            w: 2,
            h: 2,
            i: "25",
          },
          {
            x: 4,
            y: 20,
            w: 2,
            h: 5,
            i: "26",
          },
          {
            x: 6,
            y: 16,
            w: 2,
            h: 4,
            i: "27",
          },
          {
            x: 8,
            y: 16,
            w: 2,
            h: 4,
            i: "28",
          },
          {
            x: 10,
            y: 12,
            w: 2,
            h: 3,
            i: "29",
          },
          {
            x: 0,
            y: 20,
            w: 2,
            h: 4,
            i: "30",
          },
          {
            x: 2,
            y: 20,
            w: 2,
            h: 4,
            i: "31",
          },
          {
            x: 4,
            y: 20,
            w: 2,
            h: 4,
            i: "32",
          },
          {
            x: 6,
            y: 15,
            w: 2,
            h: 3,
            i: "33",
          },
          {
            x: 8,
            y: 15,
            w: 2,
            h: 3,
            i: "34",
          },
          {
            x: 10,
            y: 20,
            w: 2,
            h: 4,
            i: "35",
          },
          {
            x: 0,
            y: 12,
            w: 2,
            h: 2,
            i: "36",
          },
          {
            x: 2,
            y: 30,
            w: 2,
            h: 5,
            i: "37",
          },
          {
            x: 4,
            y: 12,
            w: 2,
            h: 2,
            i: "38",
          },
          {
            x: 6,
            y: 12,
            w: 2,
            h: 2,
            i: "39",
          },
          {
            x: 8,
            y: 18,
            w: 2,
            h: 3,
            i: "40",
          },
          {
            x: 10,
            y: 30,
            w: 2,
            h: 5,
            i: "41",
          },
          {
            x: 0,
            y: 21,
            w: 2,
            h: 3,
            i: "42",
          },
          {
            x: 2,
            y: 28,
            w: 2,
            h: 4,
            i: "43",
          },
          {
            x: 4,
            y: 21,
            w: 2,
            h: 3,
            i: "44",
          },
          {
            x: 6,
            y: 35,
            w: 2,
            h: 5,
            i: "45",
          },
          {
            x: 8,
            y: 21,
            w: 2,
            h: 3,
            i: "46",
          },
          {
            x: 10,
            y: 21,
            w: 2,
            h: 3,
            i: "47",
          },
          {
            x: 0,
            y: 40,
            w: 2,
            h: 5,
            i: "48",
          },
          {
            x: 2,
            y: 40,
            w: 2,
            h: 5,
            i: "49",
          },
        ],
      },

      // This turns off compaction so you can place items wherever.
      verticalCompact: false,
      // This turns off rearrangement so items will not be pushed arround.
      preventCollision: true,
    },
    additionalProps: {},
  },
  errorCase: {
    defaultProps: {
      className: "layout",
      items: 3,
      rowHeight: 100,
      layout: {
        lg: [
          {
            x: 0,
            y: 0,
            w: 1,
            h: 1,
            i: "1",
          },
          {
            x: 1,
            y: 0,
            w: 1,
            h: 1,
            i: "2",
          },
          {
            x: 0,
            y: 1,
            w: 2,
            h: 2,
            i: "3",
          },
        ],
      },
      cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
    },
    additionalProps: {},
  },
  toolbox: {
    defaultProps: {
      className: "layout",
      rowHeight: 30,
      layout: {
        lg: [
          {
            x: 0,
            y: 0,
            w: 1,
            h: 1,
            i: "1",
          },
          {
            x: 1,
            y: 0,
            w: 1,
            h: 1,
            i: "2",
          },
          {
            x: 0,
            y: 1,
            w: 2,
            h: 2,
            i: "3",
          },
        ],
      },

      cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
    },
    additionalProps: {},
  },
  dragFromOutside: {
    defaultProps: {
      className: "layout",
      rowHeight: 30,
      layout: {
        lg: [
          {
            w: 2,
            h: 5,
            x: 0,
            y: 0,
            i: "0",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 5,
            x: 6,
            y: 0,
            i: "1",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 2,
            x: 2,
            y: 0,
            i: "2",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 5,
            x: 4,
            y: 0,
            i: "3",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 4,
            x: 4,
            y: 0,
            i: "4",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 2,
            x: 4,
            y: 0,
            i: "5",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 5,
            x: 0,
            y: 5,
            i: "6",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 3,
            x: 2,
            y: 3,
            i: "7",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 3,
            x: 2,
            y: 3,
            i: "8",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 5,
            x: 4,
            y: 5,
            i: "9",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 5,
            x: 4,
            y: 5,
            i: "10",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 3,
            x: 4,
            y: 3,
            i: "11",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 5,
            x: 0,
            y: 10,
            i: "12",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 3,
            x: 8,
            y: 6,
            i: "13",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 2,
            x: 2,
            y: 4,
            i: "14",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 4,
            x: 4,
            y: 8,
            i: "15",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 5,
            x: 4,
            y: 10,
            i: "16",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 2,
            x: 4,
            y: 4,
            i: "17",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 2,
            x: 10,
            y: 6,
            i: "18",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 3,
            x: 4,
            y: 9,
            i: "19",
            moved: false,
            static: true,
          },
          {
            w: 2,
            h: 5,
            x: 8,
            y: 15,
            i: "20",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 2,
            x: 8,
            y: 6,
            i: "21",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 4,
            x: 4,
            y: 12,
            i: "22",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 2,
            x: 8,
            y: 6,
            i: "23",
            moved: false,
            static: false,
          },
          {
            w: 2,
            h: 4,
            x: 6,
            y: 16,
            i: "24",
            moved: false,
            static: false,
          },
        ],
      },

      cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
    },
    additionalProps: {},
  },
  bounded: {
    defaultProps: {
      className: "layout",
      items: 20,
      rowHeight: 30,
      layout: {
        lg: [
          {
            x: 0,
            y: 0,
            w: 2,
            h: 4,
            i: "0",
          },
          {
            x: 2,
            y: 0,
            w: 2,
            h: 4,
            i: "1",
          },
          {
            x: 4,
            y: 0,
            w: 2,
            h: 3,
            i: "2",
          },
          {
            x: 6,
            y: 0,
            w: 2,
            h: 4,
            i: "3",
          },
          {
            x: 8,
            y: 0,
            w: 2,
            h: 3,
            i: "4",
          },
          {
            x: 10,
            y: 0,
            w: 2,
            h: 5,
            i: "5",
          },
          {
            x: 0,
            y: 2,
            w: 2,
            h: 2,
            i: "6",
          },
          {
            x: 2,
            y: 3,
            w: 2,
            h: 3,
            i: "7",
          },
          {
            x: 4,
            y: 3,
            w: 2,
            h: 3,
            i: "8",
          },
          {
            x: 6,
            y: 4,
            w: 2,
            h: 4,
            i: "9",
          },
          {
            x: 8,
            y: 2,
            w: 2,
            h: 2,
            i: "10",
          },
          {
            x: 10,
            y: 3,
            w: 2,
            h: 3,
            i: "11",
          },
          {
            x: 0,
            y: 4,
            w: 2,
            h: 2,
            i: "12",
          },
          {
            x: 2,
            y: 8,
            w: 2,
            h: 4,
            i: "13",
          },
          {
            x: 4,
            y: 10,
            w: 2,
            h: 5,
            i: "14",
          },
          {
            x: 6,
            y: 8,
            w: 2,
            h: 4,
            i: "15",
          },
          {
            x: 8,
            y: 10,
            w: 2,
            h: 5,
            i: "16",
          },
          {
            x: 10,
            y: 6,
            w: 2,
            h: 3,
            i: "17",
          },
          {
            x: 0,
            y: 15,
            w: 2,
            h: 5,
            i: "18",
          },
          {
            x: 2,
            y: 6,
            w: 2,
            h: 2,
            i: "19",
          },
        ],
      },

      cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
    },
    additionalProps: {},
  },
  responsiveBootstrapStyle: {
    defaultProps: {
      isDraggable: true,
      isResizable: true,
      items: 20,
      rowHeight: 30,
      layout: {
        lg: [
          {
            w: 3,
            h: 4,
            x: 0,
            y: 0,
            i: "0",
            moved: false,
            static: false,
          },
          {
            w: 3,
            h: 4,
            x: 3,
            y: 0,
            i: "1",
            moved: false,
            static: false,
          },
          {
            w: 3,
            h: 4,
            x: 6,
            y: 0,
            i: "2",
            moved: false,
            static: false,
          },
          {
            w: 3,
            h: 4,
            x: 9,
            y: 0,
            i: "3",
            moved: false,
            static: false,
          },
          {
            w: 3,
            h: 4,
            x: 0,
            y: 0,
            i: "4",
            moved: false,
            static: false,
          },
          {
            w: 3,
            h: 4,
            x: 3,
            y: 0,
            i: "5",
            moved: false,
            static: false,
          },
          {
            w: 3,
            h: 4,
            x: 6,
            y: 0,
            i: "6",
            moved: false,
            static: false,
          },
          {
            w: 3,
            h: 4,
            x: 9,
            y: 0,
            i: "7",
            moved: false,
            static: false,
          },
          {
            w: 3,
            h: 4,
            x: 0,
            y: 0,
            i: "8",
            moved: false,
            static: false,
          },
          {
            w: 3,
            h: 4,
            x: 3,
            y: 0,
            i: "9",
            moved: false,
            static: false,
          },
          {
            w: 3,
            h: 4,
            x: 6,
            y: 0,
            i: "10",
            moved: false,
            static: false,
          },
          {
            w: 3,
            h: 4,
            x: 9,
            y: 0,
            i: "11",
            moved: false,
            static: false,
          },
          {
            w: 3,
            h: 4,
            x: 0,
            y: 0,
            i: "12",
            moved: false,
            static: false,
          },
          {
            w: 3,
            h: 4,
            x: 3,
            y: 0,
            i: "13",
            moved: false,
            static: false,
          },
          {
            w: 3,
            h: 4,
            x: 6,
            y: 0,
            i: "14",
            moved: false,
            static: false,
          },
          {
            w: 3,
            h: 4,
            x: 9,
            y: 0,
            i: "15",
            moved: false,
            static: false,
          },
          {
            w: 3,
            h: 4,
            x: 0,
            y: 0,
            i: "16",
            moved: false,
            static: false,
          },
          {
            w: 3,
            h: 4,
            x: 3,
            y: 0,
            i: "17",
            moved: false,
            static: false,
          },
          {
            w: 3,
            h: 4,
            x: 6,
            y: 0,
            i: "18",
            moved: false,
            static: false,
          },
          {
            w: 3,
            h: 4,
            x: 9,
            y: 0,
            i: "19",
            moved: false,
            static: false,
          },
        ],
      },

      cols: { lg: 12, md: 12, sm: 12, xs: 12, xxs: 12 },
    },
    additionalProps: {},
  },
  scale: {
    defaultProps: {
      className: "layout",
      items: 20,
      rowHeight: 30,
      layout: {
        lg: [
          {
            x: 0,
            y: 0,
            w: 2,
            h: 5,
            i: "0",
          },
          {
            x: 2,
            y: 0,
            w: 2,
            h: 5,
            i: "1",
          },
          {
            x: 4,
            y: 0,
            w: 2,
            h: 5,
            i: "2",
          },
          {
            x: 6,
            y: 0,
            w: 2,
            h: 3,
            i: "3",
          },
          {
            x: 8,
            y: 0,
            w: 2,
            h: 5,
            i: "4",
          },
          {
            x: 10,
            y: 0,
            w: 2,
            h: 5,
            i: "5",
          },
          {
            x: 0,
            y: 4,
            w: 2,
            h: 4,
            i: "6",
          },
          {
            x: 2,
            y: 3,
            w: 2,
            h: 3,
            i: "7",
          },
          {
            x: 4,
            y: 5,
            w: 2,
            h: 5,
            i: "8",
          },
          {
            x: 6,
            y: 4,
            w: 2,
            h: 4,
            i: "9",
          },
          {
            x: 8,
            y: 5,
            w: 2,
            h: 5,
            i: "10",
          },
          {
            x: 10,
            y: 5,
            w: 2,
            h: 5,
            i: "11",
          },
          {
            x: 0,
            y: 8,
            w: 2,
            h: 4,
            i: "12",
          },
          {
            x: 2,
            y: 6,
            w: 2,
            h: 3,
            i: "13",
          },
          {
            x: 4,
            y: 10,
            w: 2,
            h: 5,
            i: "14",
          },
          {
            x: 6,
            y: 4,
            w: 2,
            h: 2,
            i: "15",
          },
          {
            x: 8,
            y: 6,
            w: 2,
            h: 3,
            i: "16",
          },
          {
            x: 10,
            y: 4,
            w: 2,
            h: 2,
            i: "17",
          },
          {
            x: 0,
            y: 12,
            w: 2,
            h: 4,
            i: "18",
          },
          {
            x: 2,
            y: 6,
            w: 2,
            h: 2,
            i: "19",
          },
        ],
      },

      cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
      transformScale: 0.5,
    },
    additionalProps: {},
  },
  allowOverlap: {
    defaultProps: {
      className: "layout",
      items: 20,
      rowHeight: 30,
      layout: {
        lg: [
          {
            x: 0,
            y: 0,
            w: 2,
            h: 5,
            i: "0",
          },
          {
            x: 2,
            y: 0,
            w: 2,
            h: 3,
            i: "1",
          },
          {
            x: 4,
            y: 0,
            w: 2,
            h: 2,
            i: "2",
          },
          {
            x: 6,
            y: 0,
            w: 2,
            h: 2,
            i: "3",
          },
          {
            x: 8,
            y: 0,
            w: 2,
            h: 5,
            i: "4",
          },
          {
            x: 10,
            y: 0,
            w: 2,
            h: 3,
            i: "5",
          },
          {
            x: 0,
            y: 4,
            w: 2,
            h: 4,
            i: "6",
          },
          {
            x: 2,
            y: 2,
            w: 2,
            h: 2,
            i: "7",
          },
          {
            x: 4,
            y: 2,
            w: 2,
            h: 2,
            i: "8",
          },
          {
            x: 6,
            y: 4,
            w: 2,
            h: 4,
            i: "9",
          },
          {
            x: 8,
            y: 3,
            w: 2,
            h: 3,
            i: "10",
          },
          {
            x: 10,
            y: 2,
            w: 2,
            h: 2,
            i: "11",
          },
          {
            x: 0,
            y: 10,
            w: 2,
            h: 5,
            i: "12",
          },
          {
            x: 2,
            y: 8,
            w: 2,
            h: 4,
            i: "13",
          },
          {
            x: 4,
            y: 6,
            w: 2,
            h: 3,
            i: "14",
          },
          {
            x: 6,
            y: 6,
            w: 2,
            h: 3,
            i: "15",
          },
          {
            x: 8,
            y: 10,
            w: 2,
            h: 5,
            i: "16",
          },
          {
            x: 10,
            y: 4,
            w: 2,
            h: 2,
            i: "17",
          },
          {
            x: 0,
            y: 12,
            w: 2,
            h: 4,
            i: "18",
          },
          {
            x: 2,
            y: 15,
            w: 2,
            h: 5,
            i: "19",
          },
        ],
      },

      cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
    },
    additionalProps: {},
  },
  resizableHandles: {
    defaultProps: {
      className: "layout",
      items: 20,
      rowHeight: 30,
      layout: {
        lg: [
          {
            x: 0,
            y: 0,
            w: 2,
            h: 5,
            i: "0",
            resizeHandles: ["s", "w", "e", "n", "sw", "nw", "se", "ne"],
          },
          {
            x: 2,
            y: 0,
            w: 2,
            h: 3,
            i: "1",
          },
          {
            x: 4,
            y: 0,
            w: 2,
            h: 5,
            i: "2",
          },
          {
            x: 6,
            y: 0,
            w: 2,
            h: 2,
            i: "3",
          },
          {
            x: 8,
            y: 0,
            w: 2,
            h: 5,
            i: "4",
          },
          {
            x: 10,
            y: 0,
            w: 2,
            h: 4,
            i: "5",
          },
          {
            x: 0,
            y: 5,
            w: 2,
            h: 5,
            i: "6",
          },
          {
            x: 2,
            y: 2,
            w: 2,
            h: 2,
            i: "7",
          },
          {
            x: 4,
            y: 4,
            w: 2,
            h: 4,
            i: "8",
          },
          {
            x: 6,
            y: 5,
            w: 2,
            h: 5,
            i: "9",
          },
          {
            x: 8,
            y: 4,
            w: 2,
            h: 4,
            i: "10",
          },
          {
            x: 10,
            y: 4,
            w: 2,
            h: 4,
            i: "11",
          },
          {
            x: 0,
            y: 6,
            w: 2,
            h: 3,
            i: "12",
          },
          {
            x: 2,
            y: 8,
            w: 2,
            h: 4,
            i: "13",
          },
          {
            x: 4,
            y: 4,
            w: 2,
            h: 2,
            i: "14",
          },
          {
            x: 6,
            y: 8,
            w: 2,
            h: 4,
            i: "15",
          },
          {
            x: 8,
            y: 4,
            w: 2,
            h: 2,
            i: "16",
          },
          {
            x: 10,
            y: 6,
            w: 2,
            h: 3,
            i: "17",
          },
          {
            x: 0,
            y: 6,
            w: 2,
            h: 2,
            i: "18",
          },
          {
            x: 2,
            y: 6,
            w: 2,
            h: 2,
            i: "19",
          },
        ],
      },

      cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
    },
    additionalProps: {},
  },
  horizontal: {
    defaultProps: {
      className: "layout",
      items: 5,
      rowHeight: 5,

      cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
      compactType: "horizontal",
      maxRows: 1,
      allowOverlap: false,
      layout: {
        lg: [
          {
            x: 0,
            y: 0,
            w: 2,
            h: 5,
            i: "0",
          },
          {
            x: 2,
            y: 0,
            w: 2,
            h: 5,
            i: "1",
          },
          {
            x: 4,
            y: 0,
            w: 2,
            h: 5,
            i: "2",
          },
          {
            x: 6,
            y: 0,
            w: 2,
            h: 5,
            i: "3",
          },
          {
            x: 8,
            y: 0,
            w: 2,
            h: 5,
            i: "4",
          },
        ],
      },
    },
    additionalProps: {},
  },
} as any;

export const getPresetList = () => {
  const groups = [
    {
      name: "empty",
      enabled: false,
      group: "misc",
    },
    {
      name: "showcase",
      enabled: true,
      group: "misc",
    },
    {
      name: "basic",
      enabled: true,
      group: "misc",
    },
    {
      name: "noDragging",
      enabled: true,
      group: "interaction",
    },
    {
      name: "messy",
      enabled: true,
      group: "layout",
    },
    {
      name: "gridProperty",
      enabled: true,
      group: "layout",
    },
    {
      name: "staticElements",
      enabled: true,
      group: "misc",
    },
    {
      name: "dynamicAddRemove",
      enabled: true,
      group: "interaction",
    },
    {
      name: "localStorage",
      enabled: true,
      group: "misc",
    },
    {
      name: "localStorageResponsive",
      enabled: true,
      group: "misc",
    },
    {
      name: "minMax",
      enabled: true,
      group: "layout",
    },
    {
      name: "dynamicMinMax",
      enabled: true,
      group: "layout",
    },
    {
      name: "noVerticalCompact",
      enabled: true,
      group: "layout",
    },
    {
      name: "preventCollision",
      enabled: true,
      group: "interaction",
    },
    {
      name: "errorCase",
      enabled: true,
      group: "misc",
    },
    {
      name: "toolbox",
      enabled: true,
      group: "misc",
    },
    {
      name: "dragFromOutside",
      enabled: true,
      group: "interaction",
    },
    {
      name: "bounded",
      enabled: true,
      group: "layout",
    },
    {
      name: "responsiveBootstrapStyle",
      enabled: true,
      group: "layout",
    },
    {
      name: "scale",
      enabled: true,
      group: "layout",
    },
    {
      name: "allowOverlap",
      enabled: true,
      group: "interaction",
    },
    {
      name: "resizableHandles",
      enabled: true,
      group: "interaction",
    },
    {
      name: "horizontal",
      enabled: true,
      group: "layout",
    },
  ];

  return Object.keys(data).map((key) => ({
    name: key,
    enabled: data[key]?.additionalProps?.disabled !== true,
    group:
      groups.find(
        (g) => g.name === key && typeof g.group === "string" && g.group,
      )?.group || "misc",
  }));
};

export const getInitialState = (name: string) => {
  const scopedData = data[name];
  const { defaultProps, additionalProps } = scopedData;

  return {
    defaultProps: {
      ...defaultProps,
    },
    additionalProps: {
      ...additionalProps,
      mounted: additionalProps?.mounted ?? false,
      name: name,
    },
  };
};

/*

export const getInitialState = (name: string) => {
  const scopedData = data[name];
  const { defaultProps, additionalProps } = scopedData;

  console.log('====scopedData====', scopedData);

  const isResponsive =
    defaultProps?.layouts || additionalProps?.responsive === true;

  const layoutKeyName = isResponsive ? "layouts" : "layout";
  const layout =
    isResponsive && defaultProps.layouts?.lg?.length > 0
      ? defaultProps.layouts
      : defaultProps.layout;

  const returnedState = {
    ...omit(defaultProps, ["layout", "layouts"]),
    [layoutKeyName]: layout,
  };

  console.log(`getInitialState: ${name}: `, returnedState);
  return {
    state: {
      ...returnedState,
    },
    additionalStates: {
      isResponsive: isResponsive,
      mounted: scopedData.additionalStates?.mounted ?? false,
    }
  };
};


 */

const capture: any = {
  allowOverlap: false,
  autoSize: true,
  className: "layout",
  cols: 12,
  compactType: "vertical",
  containerPadding: null,
  draggableCancel: "",
  draggableHandle: "",
  droppingItem: {
    i: "__dropping-elem__",
    h: 1,
    w: 1,
  },
  isBounded: false,
  isDraggable: true,
  isDroppable: false,
  isResizable: true,
  margin: [10, 10],
  maxRows: null,
  onDrag: "function",
  onDragStart: "function",
  onDragStop: "function",
  onDrop: "function",
  onDropDragOver: "function",
  onLayoutChange: "function",
  onResize: "function",
  onResizeStart: "function",
  onResizeStop: "function",
  preventCollision: false,
  resizeHandles: ["se"],
  rowHeight: 150,
  style: {},
  transformScale: 1,
  useCSSTransforms: true,
  verticalCompact: true,
  layout: {
    lg: [
      {
        w: 2,
        h: 2,
        x: 2,
        y: 0,
        i: "0",
        static: false,
        resizeHandles: ["se"],
      },
      {
        w: 2,
        h: 5,
        x: 2,
        y: 0,
        i: "1",
        static: false,
        resizeHandles: ["se"],
      },
      {
        w: 2,
        h: 2,
        x: 8,
        y: 0,
        i: "2",
        static: false,
        resizeHandles: ["se"],
      },
      {
        w: 2,
        h: 3,
        x: 2,
        y: 0,
        i: "3",
        static: false,
        resizeHandles: ["se"],
      },
      {
        w: 2,
        h: 3,
        x: 4,
        y: 0,
        i: "4",
        static: false,
        resizeHandles: ["se"],
      },
      {
        w: 2,
        h: 5,
        x: 8,
        y: 0,
        i: "5",
        static: false,
        resizeHandles: ["se"],
      },
      {
        w: 2,
        h: 4,
        x: 2,
        y: 4,
        i: "6",
        static: false,
        resizeHandles: ["se"],
      },
      {
        w: 2,
        h: 5,
        x: 10,
        y: 5,
        i: "7",
        static: false,
        resizeHandles: ["se"],
      },
      {
        w: 2,
        h: 5,
        x: 4,
        y: 5,
        i: "8",
        static: false,
        resizeHandles: ["se"],
      },
      {
        w: 2,
        h: 3,
        x: 8,
        y: 3,
        i: "9",
        static: false,
        resizeHandles: ["se"],
      },
      {
        w: 2,
        h: 4,
        x: 6,
        y: 4,
        i: "10",
        static: false,
        resizeHandles: ["se"],
      },
      {
        w: 2,
        h: 2,
        x: 4,
        y: 2,
        i: "11",
        static: false,
        resizeHandles: ["se"],
      },
      {
        w: 2,
        h: 4,
        x: 2,
        y: 8,
        i: "12",
        static: false,
        resizeHandles: ["se"],
      },
      {
        w: 2,
        h: 3,
        x: 8,
        y: 6,
        i: "13",
        static: false,
        resizeHandles: ["se"],
      },
      {
        w: 2,
        h: 2,
        x: 2,
        y: 4,
        i: "14",
        static: false,
        resizeHandles: ["se"],
      },
      {
        w: 2,
        h: 3,
        x: 8,
        y: 6,
        i: "15",
        static: false,
        resizeHandles: ["se"],
      },
      {
        w: 2,
        h: 4,
        x: 4,
        y: 8,
        i: "16",
        static: false,
        resizeHandles: ["se"],
      },
      {
        w: 2,
        h: 4,
        x: 6,
        y: 8,
        i: "17",
        static: false,
        resizeHandles: ["se"],
      },
      {
        w: 2,
        h: 3,
        x: 6,
        y: 9,
        i: "18",
        static: false,
        resizeHandles: ["se"],
      },
      {
        w: 2,
        h: 2,
        x: 2,
        y: 6,
        i: "19",
        static: false,
        resizeHandles: ["se"],
      },
      {
        w: 2,
        h: 3,
        x: 8,
        y: 9,
        i: "20",
        static: false,
        resizeHandles: ["se"],
      },
      {
        w: 2,
        h: 4,
        x: 4,
        y: 12,
        i: "21",
        static: false,
        resizeHandles: ["se"],
      },
      {
        w: 2,
        h: 3,
        x: 6,
        y: 9,
        i: "22",
        static: false,
        resizeHandles: ["se"],
      },
      {
        w: 2,
        h: 3,
        x: 6,
        y: 9,
        i: "23",
        static: false,
        resizeHandles: ["se"],
      },
      {
        w: 2,
        h: 3,
        x: 8,
        y: 12,
        i: "24",
        static: false,
        resizeHandles: ["se"],
      },
    ],
  },
  layouts: {
    lg: [
      {
        x: 0,
        y: 0,
        w: 3,
        h: 4,
        i: "0",
      },
      {
        x: 3,
        y: 0,
        w: 3,
        h: 4,
        i: "1",
      },
      {
        x: 6,
        y: 0,
        w: 3,
        h: 4,
        i: "2",
      },
      {
        x: 9,
        y: 0,
        w: 3,
        h: 4,
        i: "3",
      },
      {
        x: 0,
        y: 0,
        w: 3,
        h: 4,
        i: "4",
      },
      {
        x: 3,
        y: 0,
        w: 3,
        h: 4,
        i: "5",
      },
      {
        x: 6,
        y: 0,
        w: 3,
        h: 4,
        i: "6",
      },
      {
        x: 9,
        y: 0,
        w: 3,
        h: 4,
        i: "7",
      },
      {
        x: 0,
        y: 0,
        w: 3,
        h: 4,
        i: "8",
      },
      {
        x: 3,
        y: 0,
        w: 3,
        h: 4,
        i: "9",
      },
      {
        x: 6,
        y: 0,
        w: 3,
        h: 4,
        i: "10",
      },
      {
        x: 9,
        y: 0,
        w: 3,
        h: 4,
        i: "11",
      },
      {
        x: 0,
        y: 0,
        w: 3,
        h: 4,
        i: "12",
      },
      {
        x: 3,
        y: 0,
        w: 3,
        h: 4,
        i: "13",
      },
      {
        x: 6,
        y: 0,
        w: 3,
        h: 4,
        i: "14",
      },
      {
        x: 9,
        y: 0,
        w: 3,
        h: 4,
        i: "15",
      },
      {
        x: 0,
        y: 0,
        w: 3,
        h: 4,
        i: "16",
      },
      {
        x: 3,
        y: 0,
        w: 3,
        h: 4,
        i: "17",
      },
      {
        x: 6,
        y: 0,
        w: 3,
        h: 4,
        i: "18",
      },
      {
        x: 9,
        y: 0,
        w: 3,
        h: 4,
        i: "19",
      },
    ],
    md: [
      {
        x: 0,
        y: 0,
        w: 4,
        h: 4,
        i: "0",
      },
      {
        x: 4,
        y: 0,
        w: 4,
        h: 4,
        i: "1",
      },
      {
        x: 8,
        y: 0,
        w: 4,
        h: 4,
        i: "2",
      },
      {
        x: 0,
        y: 0,
        w: 4,
        h: 4,
        i: "3",
      },
      {
        x: 4,
        y: 0,
        w: 4,
        h: 4,
        i: "4",
      },
      {
        x: 8,
        y: 0,
        w: 4,
        h: 4,
        i: "5",
      },
      {
        x: 0,
        y: 0,
        w: 4,
        h: 4,
        i: "6",
      },
      {
        x: 4,
        y: 0,
        w: 4,
        h: 4,
        i: "7",
      },
      {
        x: 8,
        y: 0,
        w: 4,
        h: 4,
        i: "8",
      },
      {
        x: 0,
        y: 0,
        w: 4,
        h: 4,
        i: "9",
      },
      {
        x: 4,
        y: 0,
        w: 4,
        h: 4,
        i: "10",
      },
      {
        x: 8,
        y: 0,
        w: 4,
        h: 4,
        i: "11",
      },
      {
        x: 0,
        y: 0,
        w: 4,
        h: 4,
        i: "12",
      },
      {
        x: 4,
        y: 0,
        w: 4,
        h: 4,
        i: "13",
      },
      {
        x: 8,
        y: 0,
        w: 4,
        h: 4,
        i: "14",
      },
      {
        x: 0,
        y: 0,
        w: 4,
        h: 4,
        i: "15",
      },
      {
        x: 4,
        y: 0,
        w: 4,
        h: 4,
        i: "16",
      },
      {
        x: 8,
        y: 0,
        w: 4,
        h: 4,
        i: "17",
      },
      {
        x: 0,
        y: 0,
        w: 4,
        h: 4,
        i: "18",
      },
      {
        x: 4,
        y: 0,
        w: 4,
        h: 4,
        i: "19",
      },
    ],
    sm: [
      {
        x: 0,
        y: 0,
        w: 6,
        h: 4,
        i: "0",
      },
      {
        x: 6,
        y: 0,
        w: 6,
        h: 4,
        i: "1",
      },
      {
        x: 0,
        y: 0,
        w: 6,
        h: 4,
        i: "2",
      },
      {
        x: 6,
        y: 0,
        w: 6,
        h: 4,
        i: "3",
      },
      {
        x: 0,
        y: 0,
        w: 6,
        h: 4,
        i: "4",
      },
      {
        x: 6,
        y: 0,
        w: 6,
        h: 4,
        i: "5",
      },
      {
        x: 0,
        y: 0,
        w: 6,
        h: 4,
        i: "6",
      },
      {
        x: 6,
        y: 0,
        w: 6,
        h: 4,
        i: "7",
      },
      {
        x: 0,
        y: 0,
        w: 6,
        h: 4,
        i: "8",
      },
      {
        x: 6,
        y: 0,
        w: 6,
        h: 4,
        i: "9",
      },
      {
        x: 0,
        y: 0,
        w: 6,
        h: 4,
        i: "10",
      },
      {
        x: 6,
        y: 0,
        w: 6,
        h: 4,
        i: "11",
      },
      {
        x: 0,
        y: 0,
        w: 6,
        h: 4,
        i: "12",
      },
      {
        x: 6,
        y: 0,
        w: 6,
        h: 4,
        i: "13",
      },
      {
        x: 0,
        y: 0,
        w: 6,
        h: 4,
        i: "14",
      },
      {
        x: 6,
        y: 0,
        w: 6,
        h: 4,
        i: "15",
      },
      {
        x: 0,
        y: 0,
        w: 6,
        h: 4,
        i: "16",
      },
      {
        x: 6,
        y: 0,
        w: 6,
        h: 4,
        i: "17",
      },
      {
        x: 0,
        y: 0,
        w: 6,
        h: 4,
        i: "18",
      },
      {
        x: 6,
        y: 0,
        w: 6,
        h: 4,
        i: "19",
      },
    ],
    xs: [
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "0",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "1",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "2",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "3",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "4",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "5",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "6",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "7",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "8",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "9",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "10",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "11",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "12",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "13",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "14",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "15",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "16",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "17",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "18",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "19",
      },
    ],
    xxs: [
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "0",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "1",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "2",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "3",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "4",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "5",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "6",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "7",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "8",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "9",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "10",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "11",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "12",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "13",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "14",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "15",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "16",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "17",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "18",
      },
      {
        x: 0,
        y: 0,
        w: 12,
        h: 4,
        i: "19",
      },
    ],
  },
};
